// ==========================================================================
// AUTO-GENERATED — DO NOT EDIT BY HAND
// Generated by: python/uwoc_lut_gen.py
// Timestamp: 2026-08-06 22:15:21
// ==========================================================================
// Model: h = L(d,λ,water) · h_s · h_o   (Salcedo-Serrano ICC'22 eq.2)
// λ = 450 nm   μ_ref = 0.1   η_det = 0.18
// Y₀ = 1.300000e-05   f_rep = 1.000e+07 Hz
// τ_coh = 5.0 ms → coherence block = 50,000 pulses
// Monitoring window used to compute nexp_inv_rom: 65,536 attempts
//
// Conventions:
//   h_s, h_o : 8-bit, 256 = mean (h = 1.0), saturating at 4095
//   probability: 16-bit, p ↔ round(p·16777216), saturating at 16777215
//   mu_level : 4-bit, 8 = nominal μ
//
// water_type order: 0=clear ocean, 1=coastal, 2=harbor
// ==========================================================================

// ---- Range grid [m] per water type (reference / UART only) ----
//   water 0 (Clear ocean): 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80
//   water 1 (Coastal): 2, 4, 6, 8, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43
//   water 2 (Harbor (turbid)): 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 7, 8, 9, 10

// ---- σ_s² for each h_s class ----
//   class 0: σ_s² = 0
//   class 1: σ_s² = 0.02
//   class 2: σ_s² = 0.05
//   class 3: σ_s² = 0.12
//   class 4: σ_s² = 0.3
//   class 5: σ_s² = 0.75
//   class 6: σ_s² = 1.8
//   class 7: σ_s² = 4.5

// ---- σ²_ho for each turbulence level (at d_ref = 20 m) ----
//   level 0 OFF      : σ²_ho =  0.0000  (—)
//   level 1 VERYWEAK : σ²_ho =  0.0200  (Lognormal)
//   level 2 WEAK     : σ²_ho =  0.0800  (Lognormal)
//   level 3 MODERATE : σ²_ho =  0.2999  (Lognormal)
//   level 4 STRONG   : σ²_ho =  1.0006  (Weibull)
//   level 5 SEVERE   : σ²_ho =  2.9996  (Weibull)

// hs_rom  : address = {hs_class[2:0], addr[7:0]}  (8×256)
reg [11:0] hs_rom [0:2047];
initial begin
    hs_rom[0]=12'd256; hs_rom[1]=12'd256; hs_rom[2]=12'd256; hs_rom[3]=12'd256; hs_rom[4]=12'd256; hs_rom[5]=12'd256; hs_rom[6]=12'd256; hs_rom[7]=12'd256;
    hs_rom[8]=12'd256; hs_rom[9]=12'd256; hs_rom[10]=12'd256; hs_rom[11]=12'd256; hs_rom[12]=12'd256; hs_rom[13]=12'd256; hs_rom[14]=12'd256; hs_rom[15]=12'd256;
    hs_rom[16]=12'd256; hs_rom[17]=12'd256; hs_rom[18]=12'd256; hs_rom[19]=12'd256; hs_rom[20]=12'd256; hs_rom[21]=12'd256; hs_rom[22]=12'd256; hs_rom[23]=12'd256;
    hs_rom[24]=12'd256; hs_rom[25]=12'd256; hs_rom[26]=12'd256; hs_rom[27]=12'd256; hs_rom[28]=12'd256; hs_rom[29]=12'd256; hs_rom[30]=12'd256; hs_rom[31]=12'd256;
    hs_rom[32]=12'd256; hs_rom[33]=12'd256; hs_rom[34]=12'd256; hs_rom[35]=12'd256; hs_rom[36]=12'd256; hs_rom[37]=12'd256; hs_rom[38]=12'd256; hs_rom[39]=12'd256;
    hs_rom[40]=12'd256; hs_rom[41]=12'd256; hs_rom[42]=12'd256; hs_rom[43]=12'd256; hs_rom[44]=12'd256; hs_rom[45]=12'd256; hs_rom[46]=12'd256; hs_rom[47]=12'd256;
    hs_rom[48]=12'd256; hs_rom[49]=12'd256; hs_rom[50]=12'd256; hs_rom[51]=12'd256; hs_rom[52]=12'd256; hs_rom[53]=12'd256; hs_rom[54]=12'd256; hs_rom[55]=12'd256;
    hs_rom[56]=12'd256; hs_rom[57]=12'd256; hs_rom[58]=12'd256; hs_rom[59]=12'd256; hs_rom[60]=12'd256; hs_rom[61]=12'd256; hs_rom[62]=12'd256; hs_rom[63]=12'd256;
    hs_rom[64]=12'd256; hs_rom[65]=12'd256; hs_rom[66]=12'd256; hs_rom[67]=12'd256; hs_rom[68]=12'd256; hs_rom[69]=12'd256; hs_rom[70]=12'd256; hs_rom[71]=12'd256;
    hs_rom[72]=12'd256; hs_rom[73]=12'd256; hs_rom[74]=12'd256; hs_rom[75]=12'd256; hs_rom[76]=12'd256; hs_rom[77]=12'd256; hs_rom[78]=12'd256; hs_rom[79]=12'd256;
    hs_rom[80]=12'd256; hs_rom[81]=12'd256; hs_rom[82]=12'd256; hs_rom[83]=12'd256; hs_rom[84]=12'd256; hs_rom[85]=12'd256; hs_rom[86]=12'd256; hs_rom[87]=12'd256;
    hs_rom[88]=12'd256; hs_rom[89]=12'd256; hs_rom[90]=12'd256; hs_rom[91]=12'd256; hs_rom[92]=12'd256; hs_rom[93]=12'd256; hs_rom[94]=12'd256; hs_rom[95]=12'd256;
    hs_rom[96]=12'd256; hs_rom[97]=12'd256; hs_rom[98]=12'd256; hs_rom[99]=12'd256; hs_rom[100]=12'd256; hs_rom[101]=12'd256; hs_rom[102]=12'd256; hs_rom[103]=12'd256;
    hs_rom[104]=12'd256; hs_rom[105]=12'd256; hs_rom[106]=12'd256; hs_rom[107]=12'd256; hs_rom[108]=12'd256; hs_rom[109]=12'd256; hs_rom[110]=12'd256; hs_rom[111]=12'd256;
    hs_rom[112]=12'd256; hs_rom[113]=12'd256; hs_rom[114]=12'd256; hs_rom[115]=12'd256; hs_rom[116]=12'd256; hs_rom[117]=12'd256; hs_rom[118]=12'd256; hs_rom[119]=12'd256;
    hs_rom[120]=12'd256; hs_rom[121]=12'd256; hs_rom[122]=12'd256; hs_rom[123]=12'd256; hs_rom[124]=12'd256; hs_rom[125]=12'd256; hs_rom[126]=12'd256; hs_rom[127]=12'd256;
    hs_rom[128]=12'd256; hs_rom[129]=12'd256; hs_rom[130]=12'd256; hs_rom[131]=12'd256; hs_rom[132]=12'd256; hs_rom[133]=12'd256; hs_rom[134]=12'd256; hs_rom[135]=12'd256;
    hs_rom[136]=12'd256; hs_rom[137]=12'd256; hs_rom[138]=12'd256; hs_rom[139]=12'd256; hs_rom[140]=12'd256; hs_rom[141]=12'd256; hs_rom[142]=12'd256; hs_rom[143]=12'd256;
    hs_rom[144]=12'd256; hs_rom[145]=12'd256; hs_rom[146]=12'd256; hs_rom[147]=12'd256; hs_rom[148]=12'd256; hs_rom[149]=12'd256; hs_rom[150]=12'd256; hs_rom[151]=12'd256;
    hs_rom[152]=12'd256; hs_rom[153]=12'd256; hs_rom[154]=12'd256; hs_rom[155]=12'd256; hs_rom[156]=12'd256; hs_rom[157]=12'd256; hs_rom[158]=12'd256; hs_rom[159]=12'd256;
    hs_rom[160]=12'd256; hs_rom[161]=12'd256; hs_rom[162]=12'd256; hs_rom[163]=12'd256; hs_rom[164]=12'd256; hs_rom[165]=12'd256; hs_rom[166]=12'd256; hs_rom[167]=12'd256;
    hs_rom[168]=12'd256; hs_rom[169]=12'd256; hs_rom[170]=12'd256; hs_rom[171]=12'd256; hs_rom[172]=12'd256; hs_rom[173]=12'd256; hs_rom[174]=12'd256; hs_rom[175]=12'd256;
    hs_rom[176]=12'd256; hs_rom[177]=12'd256; hs_rom[178]=12'd256; hs_rom[179]=12'd256; hs_rom[180]=12'd256; hs_rom[181]=12'd256; hs_rom[182]=12'd256; hs_rom[183]=12'd256;
    hs_rom[184]=12'd256; hs_rom[185]=12'd256; hs_rom[186]=12'd256; hs_rom[187]=12'd256; hs_rom[188]=12'd256; hs_rom[189]=12'd256; hs_rom[190]=12'd256; hs_rom[191]=12'd256;
    hs_rom[192]=12'd256; hs_rom[193]=12'd256; hs_rom[194]=12'd256; hs_rom[195]=12'd256; hs_rom[196]=12'd256; hs_rom[197]=12'd256; hs_rom[198]=12'd256; hs_rom[199]=12'd256;
    hs_rom[200]=12'd256; hs_rom[201]=12'd256; hs_rom[202]=12'd256; hs_rom[203]=12'd256; hs_rom[204]=12'd256; hs_rom[205]=12'd256; hs_rom[206]=12'd256; hs_rom[207]=12'd256;
    hs_rom[208]=12'd256; hs_rom[209]=12'd256; hs_rom[210]=12'd256; hs_rom[211]=12'd256; hs_rom[212]=12'd256; hs_rom[213]=12'd256; hs_rom[214]=12'd256; hs_rom[215]=12'd256;
    hs_rom[216]=12'd256; hs_rom[217]=12'd256; hs_rom[218]=12'd256; hs_rom[219]=12'd256; hs_rom[220]=12'd256; hs_rom[221]=12'd256; hs_rom[222]=12'd256; hs_rom[223]=12'd256;
    hs_rom[224]=12'd256; hs_rom[225]=12'd256; hs_rom[226]=12'd256; hs_rom[227]=12'd256; hs_rom[228]=12'd256; hs_rom[229]=12'd256; hs_rom[230]=12'd256; hs_rom[231]=12'd256;
    hs_rom[232]=12'd256; hs_rom[233]=12'd256; hs_rom[234]=12'd256; hs_rom[235]=12'd256; hs_rom[236]=12'd256; hs_rom[237]=12'd256; hs_rom[238]=12'd256; hs_rom[239]=12'd256;
    hs_rom[240]=12'd256; hs_rom[241]=12'd256; hs_rom[242]=12'd256; hs_rom[243]=12'd256; hs_rom[244]=12'd256; hs_rom[245]=12'd256; hs_rom[246]=12'd256; hs_rom[247]=12'd256;
    hs_rom[248]=12'd256; hs_rom[249]=12'd256; hs_rom[250]=12'd256; hs_rom[251]=12'd256; hs_rom[252]=12'd256; hs_rom[253]=12'd256; hs_rom[254]=12'd256; hs_rom[255]=12'd256;
    hs_rom[256]=12'd164; hs_rom[257]=12'd174; hs_rom[258]=12'd179; hs_rom[259]=12'd183; hs_rom[260]=12'd186; hs_rom[261]=12'd188; hs_rom[262]=12'd190; hs_rom[263]=12'd192;
    hs_rom[264]=12'd194; hs_rom[265]=12'd195; hs_rom[266]=12'd197; hs_rom[267]=12'd198; hs_rom[268]=12'd199; hs_rom[269]=12'd200; hs_rom[270]=12'd201; hs_rom[271]=12'd202;
    hs_rom[272]=12'd203; hs_rom[273]=12'd204; hs_rom[274]=12'd205; hs_rom[275]=12'd206; hs_rom[276]=12'd207; hs_rom[277]=12'd208; hs_rom[278]=12'd209; hs_rom[279]=12'd209;
    hs_rom[280]=12'd210; hs_rom[281]=12'd211; hs_rom[282]=12'd211; hs_rom[283]=12'd212; hs_rom[284]=12'd213; hs_rom[285]=12'd213; hs_rom[286]=12'd214; hs_rom[287]=12'd215;
    hs_rom[288]=12'd215; hs_rom[289]=12'd216; hs_rom[290]=12'd217; hs_rom[291]=12'd217; hs_rom[292]=12'd218; hs_rom[293]=12'd218; hs_rom[294]=12'd219; hs_rom[295]=12'd219;
    hs_rom[296]=12'd220; hs_rom[297]=12'd220; hs_rom[298]=12'd221; hs_rom[299]=12'd221; hs_rom[300]=12'd222; hs_rom[301]=12'd222; hs_rom[302]=12'd223; hs_rom[303]=12'd223;
    hs_rom[304]=12'd224; hs_rom[305]=12'd224; hs_rom[306]=12'd225; hs_rom[307]=12'd225; hs_rom[308]=12'd226; hs_rom[309]=12'd226; hs_rom[310]=12'd227; hs_rom[311]=12'd227;
    hs_rom[312]=12'd228; hs_rom[313]=12'd228; hs_rom[314]=12'd228; hs_rom[315]=12'd229; hs_rom[316]=12'd229; hs_rom[317]=12'd230; hs_rom[318]=12'd230; hs_rom[319]=12'd231;
    hs_rom[320]=12'd231; hs_rom[321]=12'd231; hs_rom[322]=12'd232; hs_rom[323]=12'd232; hs_rom[324]=12'd233; hs_rom[325]=12'd233; hs_rom[326]=12'd233; hs_rom[327]=12'd234;
    hs_rom[328]=12'd234; hs_rom[329]=12'd235; hs_rom[330]=12'd235; hs_rom[331]=12'd235; hs_rom[332]=12'd236; hs_rom[333]=12'd236; hs_rom[334]=12'd237; hs_rom[335]=12'd237;
    hs_rom[336]=12'd237; hs_rom[337]=12'd238; hs_rom[338]=12'd238; hs_rom[339]=12'd238; hs_rom[340]=12'd239; hs_rom[341]=12'd239; hs_rom[342]=12'd240; hs_rom[343]=12'd240;
    hs_rom[344]=12'd240; hs_rom[345]=12'd241; hs_rom[346]=12'd241; hs_rom[347]=12'd241; hs_rom[348]=12'd242; hs_rom[349]=12'd242; hs_rom[350]=12'd242; hs_rom[351]=12'd243;
    hs_rom[352]=12'd243; hs_rom[353]=12'd244; hs_rom[354]=12'd244; hs_rom[355]=12'd244; hs_rom[356]=12'd245; hs_rom[357]=12'd245; hs_rom[358]=12'd245; hs_rom[359]=12'd246;
    hs_rom[360]=12'd246; hs_rom[361]=12'd246; hs_rom[362]=12'd247; hs_rom[363]=12'd247; hs_rom[364]=12'd247; hs_rom[365]=12'd248; hs_rom[366]=12'd248; hs_rom[367]=12'd248;
    hs_rom[368]=12'd249; hs_rom[369]=12'd249; hs_rom[370]=12'd250; hs_rom[371]=12'd250; hs_rom[372]=12'd250; hs_rom[373]=12'd251; hs_rom[374]=12'd251; hs_rom[375]=12'd251;
    hs_rom[376]=12'd252; hs_rom[377]=12'd252; hs_rom[378]=12'd252; hs_rom[379]=12'd253; hs_rom[380]=12'd253; hs_rom[381]=12'd253; hs_rom[382]=12'd254; hs_rom[383]=12'd254;
    hs_rom[384]=12'd254; hs_rom[385]=12'd255; hs_rom[386]=12'd255; hs_rom[387]=12'd256; hs_rom[388]=12'd256; hs_rom[389]=12'd256; hs_rom[390]=12'd257; hs_rom[391]=12'd257;
    hs_rom[392]=12'd257; hs_rom[393]=12'd258; hs_rom[394]=12'd258; hs_rom[395]=12'd258; hs_rom[396]=12'd259; hs_rom[397]=12'd259; hs_rom[398]=12'd259; hs_rom[399]=12'd260;
    hs_rom[400]=12'd260; hs_rom[401]=12'd261; hs_rom[402]=12'd261; hs_rom[403]=12'd261; hs_rom[404]=12'd262; hs_rom[405]=12'd262; hs_rom[406]=12'd262; hs_rom[407]=12'd263;
    hs_rom[408]=12'd263; hs_rom[409]=12'd264; hs_rom[410]=12'd264; hs_rom[411]=12'd264; hs_rom[412]=12'd265; hs_rom[413]=12'd265; hs_rom[414]=12'd265; hs_rom[415]=12'd266;
    hs_rom[416]=12'd266; hs_rom[417]=12'd267; hs_rom[418]=12'd267; hs_rom[419]=12'd267; hs_rom[420]=12'd268; hs_rom[421]=12'd268; hs_rom[422]=12'd268; hs_rom[423]=12'd269;
    hs_rom[424]=12'd269; hs_rom[425]=12'd270; hs_rom[426]=12'd270; hs_rom[427]=12'd270; hs_rom[428]=12'd271; hs_rom[429]=12'd271; hs_rom[430]=12'd272; hs_rom[431]=12'd272;
    hs_rom[432]=12'd273; hs_rom[433]=12'd273; hs_rom[434]=12'd273; hs_rom[435]=12'd274; hs_rom[436]=12'd274; hs_rom[437]=12'd275; hs_rom[438]=12'd275; hs_rom[439]=12'd276;
    hs_rom[440]=12'd276; hs_rom[441]=12'd276; hs_rom[442]=12'd277; hs_rom[443]=12'd277; hs_rom[444]=12'd278; hs_rom[445]=12'd278; hs_rom[446]=12'd279; hs_rom[447]=12'd279;
    hs_rom[448]=12'd280; hs_rom[449]=12'd280; hs_rom[450]=12'd281; hs_rom[451]=12'd281; hs_rom[452]=12'd282; hs_rom[453]=12'd282; hs_rom[454]=12'd283; hs_rom[455]=12'd283;
    hs_rom[456]=12'd284; hs_rom[457]=12'd284; hs_rom[458]=12'd285; hs_rom[459]=12'd285; hs_rom[460]=12'd286; hs_rom[461]=12'd286; hs_rom[462]=12'd287; hs_rom[463]=12'd287;
    hs_rom[464]=12'd288; hs_rom[465]=12'd289; hs_rom[466]=12'd289; hs_rom[467]=12'd290; hs_rom[468]=12'd290; hs_rom[469]=12'd291; hs_rom[470]=12'd292; hs_rom[471]=12'd292;
    hs_rom[472]=12'd293; hs_rom[473]=12'd293; hs_rom[474]=12'd294; hs_rom[475]=12'd295; hs_rom[476]=12'd296; hs_rom[477]=12'd296; hs_rom[478]=12'd297; hs_rom[479]=12'd298;
    hs_rom[480]=12'd298; hs_rom[481]=12'd299; hs_rom[482]=12'd300; hs_rom[483]=12'd301; hs_rom[484]=12'd302; hs_rom[485]=12'd303; hs_rom[486]=12'd303; hs_rom[487]=12'd304;
    hs_rom[488]=12'd305; hs_rom[489]=12'd306; hs_rom[490]=12'd307; hs_rom[491]=12'd308; hs_rom[492]=12'd309; hs_rom[493]=12'd311; hs_rom[494]=12'd312; hs_rom[495]=12'd313;
    hs_rom[496]=12'd314; hs_rom[497]=12'd316; hs_rom[498]=12'd317; hs_rom[499]=12'd319; hs_rom[500]=12'd320; hs_rom[501]=12'd322; hs_rom[502]=12'd324; hs_rom[503]=12'd326;
    hs_rom[504]=12'd329; hs_rom[505]=12'd331; hs_rom[506]=12'd334; hs_rom[507]=12'd338; hs_rom[508]=12'd342; hs_rom[509]=12'd348; hs_rom[510]=12'd356; hs_rom[511]=12'd373;
    hs_rom[512]=12'd122; hs_rom[513]=12'd135; hs_rom[514]=12'd142; hs_rom[515]=12'd146; hs_rom[516]=12'd150; hs_rom[517]=12'd154; hs_rom[518]=12'd157; hs_rom[519]=12'd159;
    hs_rom[520]=12'd162; hs_rom[521]=12'd164; hs_rom[522]=12'd166; hs_rom[523]=12'd167; hs_rom[524]=12'd169; hs_rom[525]=12'd171; hs_rom[526]=12'd172; hs_rom[527]=12'd174;
    hs_rom[528]=12'd175; hs_rom[529]=12'd177; hs_rom[530]=12'd178; hs_rom[531]=12'd179; hs_rom[532]=12'd180; hs_rom[533]=12'd181; hs_rom[534]=12'd183; hs_rom[535]=12'd184;
    hs_rom[536]=12'd185; hs_rom[537]=12'd186; hs_rom[538]=12'd187; hs_rom[539]=12'd188; hs_rom[540]=12'd189; hs_rom[541]=12'd190; hs_rom[542]=12'd191; hs_rom[543]=12'd192;
    hs_rom[544]=12'd192; hs_rom[545]=12'd193; hs_rom[546]=12'd194; hs_rom[547]=12'd195; hs_rom[548]=12'd196; hs_rom[549]=12'd197; hs_rom[550]=12'd198; hs_rom[551]=12'd198;
    hs_rom[552]=12'd199; hs_rom[553]=12'd200; hs_rom[554]=12'd201; hs_rom[555]=12'd201; hs_rom[556]=12'd202; hs_rom[557]=12'd203; hs_rom[558]=12'd204; hs_rom[559]=12'd204;
    hs_rom[560]=12'd205; hs_rom[561]=12'd206; hs_rom[562]=12'd207; hs_rom[563]=12'd207; hs_rom[564]=12'd208; hs_rom[565]=12'd209; hs_rom[566]=12'd209; hs_rom[567]=12'd210;
    hs_rom[568]=12'd211; hs_rom[569]=12'd211; hs_rom[570]=12'd212; hs_rom[571]=12'd213; hs_rom[572]=12'd213; hs_rom[573]=12'd214; hs_rom[574]=12'd214; hs_rom[575]=12'd215;
    hs_rom[576]=12'd216; hs_rom[577]=12'd216; hs_rom[578]=12'd217; hs_rom[579]=12'd218; hs_rom[580]=12'd218; hs_rom[581]=12'd219; hs_rom[582]=12'd219; hs_rom[583]=12'd220;
    hs_rom[584]=12'd221; hs_rom[585]=12'd221; hs_rom[586]=12'd222; hs_rom[587]=12'd222; hs_rom[588]=12'd223; hs_rom[589]=12'd224; hs_rom[590]=12'd224; hs_rom[591]=12'd225;
    hs_rom[592]=12'd225; hs_rom[593]=12'd226; hs_rom[594]=12'd226; hs_rom[595]=12'd227; hs_rom[596]=12'd228; hs_rom[597]=12'd228; hs_rom[598]=12'd229; hs_rom[599]=12'd229;
    hs_rom[600]=12'd230; hs_rom[601]=12'd230; hs_rom[602]=12'd231; hs_rom[603]=12'd232; hs_rom[604]=12'd232; hs_rom[605]=12'd233; hs_rom[606]=12'd233; hs_rom[607]=12'd234;
    hs_rom[608]=12'd234; hs_rom[609]=12'd235; hs_rom[610]=12'd236; hs_rom[611]=12'd236; hs_rom[612]=12'd237; hs_rom[613]=12'd237; hs_rom[614]=12'd238; hs_rom[615]=12'd238;
    hs_rom[616]=12'd239; hs_rom[617]=12'd239; hs_rom[618]=12'd240; hs_rom[619]=12'd240; hs_rom[620]=12'd241; hs_rom[621]=12'd242; hs_rom[622]=12'd242; hs_rom[623]=12'd243;
    hs_rom[624]=12'd243; hs_rom[625]=12'd244; hs_rom[626]=12'd244; hs_rom[627]=12'd245; hs_rom[628]=12'd245; hs_rom[629]=12'd246; hs_rom[630]=12'd247; hs_rom[631]=12'd247;
    hs_rom[632]=12'd248; hs_rom[633]=12'd248; hs_rom[634]=12'd249; hs_rom[635]=12'd249; hs_rom[636]=12'd250; hs_rom[637]=12'd250; hs_rom[638]=12'd251; hs_rom[639]=12'd251;
    hs_rom[640]=12'd252; hs_rom[641]=12'd253; hs_rom[642]=12'd253; hs_rom[643]=12'd254; hs_rom[644]=12'd254; hs_rom[645]=12'd255; hs_rom[646]=12'd255; hs_rom[647]=12'd256;
    hs_rom[648]=12'd256; hs_rom[649]=12'd257; hs_rom[650]=12'd258; hs_rom[651]=12'd258; hs_rom[652]=12'd259; hs_rom[653]=12'd259; hs_rom[654]=12'd260; hs_rom[655]=12'd260;
    hs_rom[656]=12'd261; hs_rom[657]=12'd262; hs_rom[658]=12'd262; hs_rom[659]=12'd263; hs_rom[660]=12'd263; hs_rom[661]=12'd264; hs_rom[662]=12'd265; hs_rom[663]=12'd265;
    hs_rom[664]=12'd266; hs_rom[665]=12'd266; hs_rom[666]=12'd267; hs_rom[667]=12'd268; hs_rom[668]=12'd268; hs_rom[669]=12'd269; hs_rom[670]=12'd269; hs_rom[671]=12'd270;
    hs_rom[672]=12'd271; hs_rom[673]=12'd271; hs_rom[674]=12'd272; hs_rom[675]=12'd272; hs_rom[676]=12'd273; hs_rom[677]=12'd274; hs_rom[678]=12'd274; hs_rom[679]=12'd275;
    hs_rom[680]=12'd276; hs_rom[681]=12'd276; hs_rom[682]=12'd277; hs_rom[683]=12'd278; hs_rom[684]=12'd278; hs_rom[685]=12'd279; hs_rom[686]=12'd279; hs_rom[687]=12'd280;
    hs_rom[688]=12'd281; hs_rom[689]=12'd281; hs_rom[690]=12'd282; hs_rom[691]=12'd283; hs_rom[692]=12'd284; hs_rom[693]=12'd284; hs_rom[694]=12'd285; hs_rom[695]=12'd286;
    hs_rom[696]=12'd286; hs_rom[697]=12'd287; hs_rom[698]=12'd288; hs_rom[699]=12'd289; hs_rom[700]=12'd289; hs_rom[701]=12'd290; hs_rom[702]=12'd291; hs_rom[703]=12'd292;
    hs_rom[704]=12'd292; hs_rom[705]=12'd293; hs_rom[706]=12'd294; hs_rom[707]=12'd295; hs_rom[708]=12'd295; hs_rom[709]=12'd296; hs_rom[710]=12'd297; hs_rom[711]=12'd298;
    hs_rom[712]=12'd299; hs_rom[713]=12'd300; hs_rom[714]=12'd300; hs_rom[715]=12'd301; hs_rom[716]=12'd302; hs_rom[717]=12'd303; hs_rom[718]=12'd304; hs_rom[719]=12'd305;
    hs_rom[720]=12'd306; hs_rom[721]=12'd307; hs_rom[722]=12'd308; hs_rom[723]=12'd309; hs_rom[724]=12'd310; hs_rom[725]=12'd311; hs_rom[726]=12'd312; hs_rom[727]=12'd313;
    hs_rom[728]=12'd314; hs_rom[729]=12'd315; hs_rom[730]=12'd316; hs_rom[731]=12'd317; hs_rom[732]=12'd318; hs_rom[733]=12'd320; hs_rom[734]=12'd321; hs_rom[735]=12'd322;
    hs_rom[736]=12'd323; hs_rom[737]=12'd325; hs_rom[738]=12'd326; hs_rom[739]=12'd327; hs_rom[740]=12'd329; hs_rom[741]=12'd330; hs_rom[742]=12'd332; hs_rom[743]=12'd333;
    hs_rom[744]=12'd335; hs_rom[745]=12'd336; hs_rom[746]=12'd338; hs_rom[747]=12'd340; hs_rom[748]=12'd342; hs_rom[749]=12'd344; hs_rom[750]=12'd346; hs_rom[751]=12'd348;
    hs_rom[752]=12'd350; hs_rom[753]=12'd353; hs_rom[754]=12'd355; hs_rom[755]=12'd358; hs_rom[756]=12'd361; hs_rom[757]=12'd364; hs_rom[758]=12'd367; hs_rom[759]=12'd371;
    hs_rom[760]=12'd375; hs_rom[761]=12'd379; hs_rom[762]=12'd385; hs_rom[763]=12'd391; hs_rom[764]=12'd398; hs_rom[765]=12'd408; hs_rom[766]=12'd423; hs_rom[767]=12'd453;
    hs_rom[768]=12'd73; hs_rom[769]=12'd87; hs_rom[770]=12'd95; hs_rom[771]=12'd101; hs_rom[772]=12'd106; hs_rom[773]=12'd110; hs_rom[774]=12'd113; hs_rom[775]=12'd116;
    hs_rom[776]=12'd119; hs_rom[777]=12'd122; hs_rom[778]=12'd124; hs_rom[779]=12'd127; hs_rom[780]=12'd129; hs_rom[781]=12'd131; hs_rom[782]=12'd133; hs_rom[783]=12'd135;
    hs_rom[784]=12'd137; hs_rom[785]=12'd138; hs_rom[786]=12'd140; hs_rom[787]=12'd142; hs_rom[788]=12'd143; hs_rom[789]=12'd145; hs_rom[790]=12'd146; hs_rom[791]=12'd148;
    hs_rom[792]=12'd149; hs_rom[793]=12'd151; hs_rom[794]=12'd152; hs_rom[795]=12'd154; hs_rom[796]=12'd155; hs_rom[797]=12'd156; hs_rom[798]=12'd157; hs_rom[799]=12'd159;
    hs_rom[800]=12'd160; hs_rom[801]=12'd161; hs_rom[802]=12'd162; hs_rom[803]=12'd163; hs_rom[804]=12'd165; hs_rom[805]=12'd166; hs_rom[806]=12'd167; hs_rom[807]=12'd168;
    hs_rom[808]=12'd169; hs_rom[809]=12'd170; hs_rom[810]=12'd171; hs_rom[811]=12'd172; hs_rom[812]=12'd173; hs_rom[813]=12'd174; hs_rom[814]=12'd175; hs_rom[815]=12'd176;
    hs_rom[816]=12'd177; hs_rom[817]=12'd178; hs_rom[818]=12'd179; hs_rom[819]=12'd180; hs_rom[820]=12'd181; hs_rom[821]=12'd182; hs_rom[822]=12'd183; hs_rom[823]=12'd184;
    hs_rom[824]=12'd185; hs_rom[825]=12'd186; hs_rom[826]=12'd187; hs_rom[827]=12'd188; hs_rom[828]=12'd189; hs_rom[829]=12'd190; hs_rom[830]=12'd191; hs_rom[831]=12'd192;
    hs_rom[832]=12'd192; hs_rom[833]=12'd193; hs_rom[834]=12'd194; hs_rom[835]=12'd195; hs_rom[836]=12'd196; hs_rom[837]=12'd197; hs_rom[838]=12'd198; hs_rom[839]=12'd199;
    hs_rom[840]=12'd199; hs_rom[841]=12'd200; hs_rom[842]=12'd201; hs_rom[843]=12'd202; hs_rom[844]=12'd203; hs_rom[845]=12'd204; hs_rom[846]=12'd205; hs_rom[847]=12'd205;
    hs_rom[848]=12'd206; hs_rom[849]=12'd207; hs_rom[850]=12'd208; hs_rom[851]=12'd209; hs_rom[852]=12'd210; hs_rom[853]=12'd211; hs_rom[854]=12'd211; hs_rom[855]=12'd212;
    hs_rom[856]=12'd213; hs_rom[857]=12'd214; hs_rom[858]=12'd215; hs_rom[859]=12'd216; hs_rom[860]=12'd216; hs_rom[861]=12'd217; hs_rom[862]=12'd218; hs_rom[863]=12'd219;
    hs_rom[864]=12'd220; hs_rom[865]=12'd221; hs_rom[866]=12'd221; hs_rom[867]=12'd222; hs_rom[868]=12'd223; hs_rom[869]=12'd224; hs_rom[870]=12'd225; hs_rom[871]=12'd225;
    hs_rom[872]=12'd226; hs_rom[873]=12'd227; hs_rom[874]=12'd228; hs_rom[875]=12'd229; hs_rom[876]=12'd230; hs_rom[877]=12'd230; hs_rom[878]=12'd231; hs_rom[879]=12'd232;
    hs_rom[880]=12'd233; hs_rom[881]=12'd234; hs_rom[882]=12'd235; hs_rom[883]=12'd235; hs_rom[884]=12'd236; hs_rom[885]=12'd237; hs_rom[886]=12'd238; hs_rom[887]=12'd239;
    hs_rom[888]=12'd240; hs_rom[889]=12'd240; hs_rom[890]=12'd241; hs_rom[891]=12'd242; hs_rom[892]=12'd243; hs_rom[893]=12'd244; hs_rom[894]=12'd245; hs_rom[895]=12'd245;
    hs_rom[896]=12'd246; hs_rom[897]=12'd247; hs_rom[898]=12'd248; hs_rom[899]=12'd249; hs_rom[900]=12'd250; hs_rom[901]=12'd251; hs_rom[902]=12'd251; hs_rom[903]=12'd252;
    hs_rom[904]=12'd253; hs_rom[905]=12'd254; hs_rom[906]=12'd255; hs_rom[907]=12'd256; hs_rom[908]=12'd257; hs_rom[909]=12'd257; hs_rom[910]=12'd258; hs_rom[911]=12'd259;
    hs_rom[912]=12'd260; hs_rom[913]=12'd261; hs_rom[914]=12'd262; hs_rom[915]=12'd263; hs_rom[916]=12'd264; hs_rom[917]=12'd265; hs_rom[918]=12'd266; hs_rom[919]=12'd266;
    hs_rom[920]=12'd267; hs_rom[921]=12'd268; hs_rom[922]=12'd269; hs_rom[923]=12'd270; hs_rom[924]=12'd271; hs_rom[925]=12'd272; hs_rom[926]=12'd273; hs_rom[927]=12'd274;
    hs_rom[928]=12'd275; hs_rom[929]=12'd276; hs_rom[930]=12'd277; hs_rom[931]=12'd278; hs_rom[932]=12'd279; hs_rom[933]=12'd280; hs_rom[934]=12'd281; hs_rom[935]=12'd282;
    hs_rom[936]=12'd283; hs_rom[937]=12'd284; hs_rom[938]=12'd285; hs_rom[939]=12'd286; hs_rom[940]=12'd287; hs_rom[941]=12'd288; hs_rom[942]=12'd289; hs_rom[943]=12'd290;
    hs_rom[944]=12'd291; hs_rom[945]=12'd292; hs_rom[946]=12'd293; hs_rom[947]=12'd294; hs_rom[948]=12'd296; hs_rom[949]=12'd297; hs_rom[950]=12'd298; hs_rom[951]=12'd299;
    hs_rom[952]=12'd300; hs_rom[953]=12'd301; hs_rom[954]=12'd302; hs_rom[955]=12'd304; hs_rom[956]=12'd305; hs_rom[957]=12'd306; hs_rom[958]=12'd307; hs_rom[959]=12'd308;
    hs_rom[960]=12'd310; hs_rom[961]=12'd311; hs_rom[962]=12'd312; hs_rom[963]=12'd313; hs_rom[964]=12'd315; hs_rom[965]=12'd316; hs_rom[966]=12'd317; hs_rom[967]=12'd319;
    hs_rom[968]=12'd320; hs_rom[969]=12'd321; hs_rom[970]=12'd323; hs_rom[971]=12'd324; hs_rom[972]=12'd326; hs_rom[973]=12'd327; hs_rom[974]=12'd329; hs_rom[975]=12'd330;
    hs_rom[976]=12'd332; hs_rom[977]=12'd333; hs_rom[978]=12'd335; hs_rom[979]=12'd336; hs_rom[980]=12'd338; hs_rom[981]=12'd340; hs_rom[982]=12'd341; hs_rom[983]=12'd343;
    hs_rom[984]=12'd345; hs_rom[985]=12'd347; hs_rom[986]=12'd349; hs_rom[987]=12'd350; hs_rom[988]=12'd352; hs_rom[989]=12'd354; hs_rom[990]=12'd356; hs_rom[991]=12'd358;
    hs_rom[992]=12'd360; hs_rom[993]=12'd363; hs_rom[994]=12'd365; hs_rom[995]=12'd367; hs_rom[996]=12'd369; hs_rom[997]=12'd372; hs_rom[998]=12'd374; hs_rom[999]=12'd377;
    hs_rom[1000]=12'd380; hs_rom[1001]=12'd382; hs_rom[1002]=12'd385; hs_rom[1003]=12'd388; hs_rom[1004]=12'd392; hs_rom[1005]=12'd395; hs_rom[1006]=12'd398; hs_rom[1007]=12'd402;
    hs_rom[1008]=12'd406; hs_rom[1009]=12'd410; hs_rom[1010]=12'd414; hs_rom[1011]=12'd419; hs_rom[1012]=12'd423; hs_rom[1013]=12'd429; hs_rom[1014]=12'd435; hs_rom[1015]=12'd441;
    hs_rom[1016]=12'd448; hs_rom[1017]=12'd456; hs_rom[1018]=12'd465; hs_rom[1019]=12'd476; hs_rom[1020]=12'd490; hs_rom[1021]=12'd507; hs_rom[1022]=12'd533; hs_rom[1023]=12'd587;
    hs_rom[1024]=12'd25; hs_rom[1025]=12'd36; hs_rom[1026]=12'd42; hs_rom[1027]=12'd48; hs_rom[1028]=12'd52; hs_rom[1029]=12'd56; hs_rom[1030]=12'd59; hs_rom[1031]=12'd62;
    hs_rom[1032]=12'd65; hs_rom[1033]=12'd68; hs_rom[1034]=12'd71; hs_rom[1035]=12'd73; hs_rom[1036]=12'd76; hs_rom[1037]=12'd78; hs_rom[1038]=12'd80; hs_rom[1039]=12'd82;
    hs_rom[1040]=12'd84; hs_rom[1041]=12'd86; hs_rom[1042]=12'd88; hs_rom[1043]=12'd90; hs_rom[1044]=12'd92; hs_rom[1045]=12'd94; hs_rom[1046]=12'd95; hs_rom[1047]=12'd97;
    hs_rom[1048]=12'd99; hs_rom[1049]=12'd100; hs_rom[1050]=12'd102; hs_rom[1051]=12'd104; hs_rom[1052]=12'd105; hs_rom[1053]=12'd107; hs_rom[1054]=12'd108; hs_rom[1055]=12'd110;
    hs_rom[1056]=12'd111; hs_rom[1057]=12'd113; hs_rom[1058]=12'd114; hs_rom[1059]=12'd116; hs_rom[1060]=12'd117; hs_rom[1061]=12'd119; hs_rom[1062]=12'd120; hs_rom[1063]=12'd121;
    hs_rom[1064]=12'd123; hs_rom[1065]=12'd124; hs_rom[1066]=12'd126; hs_rom[1067]=12'd127; hs_rom[1068]=12'd128; hs_rom[1069]=12'd130; hs_rom[1070]=12'd131; hs_rom[1071]=12'd132;
    hs_rom[1072]=12'd134; hs_rom[1073]=12'd135; hs_rom[1074]=12'd136; hs_rom[1075]=12'd137; hs_rom[1076]=12'd139; hs_rom[1077]=12'd140; hs_rom[1078]=12'd141; hs_rom[1079]=12'd143;
    hs_rom[1080]=12'd144; hs_rom[1081]=12'd145; hs_rom[1082]=12'd146; hs_rom[1083]=12'd148; hs_rom[1084]=12'd149; hs_rom[1085]=12'd150; hs_rom[1086]=12'd151; hs_rom[1087]=12'd152;
    hs_rom[1088]=12'd154; hs_rom[1089]=12'd155; hs_rom[1090]=12'd156; hs_rom[1091]=12'd157; hs_rom[1092]=12'd159; hs_rom[1093]=12'd160; hs_rom[1094]=12'd161; hs_rom[1095]=12'd162;
    hs_rom[1096]=12'd163; hs_rom[1097]=12'd165; hs_rom[1098]=12'd166; hs_rom[1099]=12'd167; hs_rom[1100]=12'd168; hs_rom[1101]=12'd169; hs_rom[1102]=12'd171; hs_rom[1103]=12'd172;
    hs_rom[1104]=12'd173; hs_rom[1105]=12'd174; hs_rom[1106]=12'd175; hs_rom[1107]=12'd177; hs_rom[1108]=12'd178; hs_rom[1109]=12'd179; hs_rom[1110]=12'd180; hs_rom[1111]=12'd181;
    hs_rom[1112]=12'd182; hs_rom[1113]=12'd184; hs_rom[1114]=12'd185; hs_rom[1115]=12'd186; hs_rom[1116]=12'd187; hs_rom[1117]=12'd188; hs_rom[1118]=12'd190; hs_rom[1119]=12'd191;
    hs_rom[1120]=12'd192; hs_rom[1121]=12'd193; hs_rom[1122]=12'd194; hs_rom[1123]=12'd196; hs_rom[1124]=12'd197; hs_rom[1125]=12'd198; hs_rom[1126]=12'd199; hs_rom[1127]=12'd200;
    hs_rom[1128]=12'd202; hs_rom[1129]=12'd203; hs_rom[1130]=12'd204; hs_rom[1131]=12'd205; hs_rom[1132]=12'd206; hs_rom[1133]=12'd208; hs_rom[1134]=12'd209; hs_rom[1135]=12'd210;
    hs_rom[1136]=12'd211; hs_rom[1137]=12'd213; hs_rom[1138]=12'd214; hs_rom[1139]=12'd215; hs_rom[1140]=12'd216; hs_rom[1141]=12'd218; hs_rom[1142]=12'd219; hs_rom[1143]=12'd220;
    hs_rom[1144]=12'd221; hs_rom[1145]=12'd223; hs_rom[1146]=12'd224; hs_rom[1147]=12'd225; hs_rom[1148]=12'd226; hs_rom[1149]=12'd228; hs_rom[1150]=12'd229; hs_rom[1151]=12'd230;
    hs_rom[1152]=12'd232; hs_rom[1153]=12'd233; hs_rom[1154]=12'd234; hs_rom[1155]=12'd235; hs_rom[1156]=12'd237; hs_rom[1157]=12'd238; hs_rom[1158]=12'd239; hs_rom[1159]=12'd241;
    hs_rom[1160]=12'd242; hs_rom[1161]=12'd243; hs_rom[1162]=12'd245; hs_rom[1163]=12'd246; hs_rom[1164]=12'd247; hs_rom[1165]=12'd249; hs_rom[1166]=12'd250; hs_rom[1167]=12'd252;
    hs_rom[1168]=12'd253; hs_rom[1169]=12'd254; hs_rom[1170]=12'd256; hs_rom[1171]=12'd257; hs_rom[1172]=12'd259; hs_rom[1173]=12'd260; hs_rom[1174]=12'd261; hs_rom[1175]=12'd263;
    hs_rom[1176]=12'd264; hs_rom[1177]=12'd266; hs_rom[1178]=12'd267; hs_rom[1179]=12'd269; hs_rom[1180]=12'd270; hs_rom[1181]=12'd272; hs_rom[1182]=12'd273; hs_rom[1183]=12'd275;
    hs_rom[1184]=12'd276; hs_rom[1185]=12'd278; hs_rom[1186]=12'd279; hs_rom[1187]=12'd281; hs_rom[1188]=12'd283; hs_rom[1189]=12'd284; hs_rom[1190]=12'd286; hs_rom[1191]=12'd287;
    hs_rom[1192]=12'd289; hs_rom[1193]=12'd291; hs_rom[1194]=12'd292; hs_rom[1195]=12'd294; hs_rom[1196]=12'd296; hs_rom[1197]=12'd297; hs_rom[1198]=12'd299; hs_rom[1199]=12'd301;
    hs_rom[1200]=12'd302; hs_rom[1201]=12'd304; hs_rom[1202]=12'd306; hs_rom[1203]=12'd308; hs_rom[1204]=12'd310; hs_rom[1205]=12'd311; hs_rom[1206]=12'd313; hs_rom[1207]=12'd315;
    hs_rom[1208]=12'd317; hs_rom[1209]=12'd319; hs_rom[1210]=12'd321; hs_rom[1211]=12'd323; hs_rom[1212]=12'd325; hs_rom[1213]=12'd327; hs_rom[1214]=12'd329; hs_rom[1215]=12'd331;
    hs_rom[1216]=12'd333; hs_rom[1217]=12'd335; hs_rom[1218]=12'd337; hs_rom[1219]=12'd339; hs_rom[1220]=12'd341; hs_rom[1221]=12'd344; hs_rom[1222]=12'd346; hs_rom[1223]=12'd348;
    hs_rom[1224]=12'd350; hs_rom[1225]=12'd353; hs_rom[1226]=12'd355; hs_rom[1227]=12'd357; hs_rom[1228]=12'd360; hs_rom[1229]=12'd362; hs_rom[1230]=12'd365; hs_rom[1231]=12'd367;
    hs_rom[1232]=12'd370; hs_rom[1233]=12'd373; hs_rom[1234]=12'd375; hs_rom[1235]=12'd378; hs_rom[1236]=12'd381; hs_rom[1237]=12'd384; hs_rom[1238]=12'd387; hs_rom[1239]=12'd390;
    hs_rom[1240]=12'd393; hs_rom[1241]=12'd396; hs_rom[1242]=12'd399; hs_rom[1243]=12'd402; hs_rom[1244]=12'd406; hs_rom[1245]=12'd409; hs_rom[1246]=12'd413; hs_rom[1247]=12'd416;
    hs_rom[1248]=12'd420; hs_rom[1249]=12'd424; hs_rom[1250]=12'd428; hs_rom[1251]=12'd432; hs_rom[1252]=12'd436; hs_rom[1253]=12'd440; hs_rom[1254]=12'd444; hs_rom[1255]=12'd449;
    hs_rom[1256]=12'd454; hs_rom[1257]=12'd459; hs_rom[1258]=12'd464; hs_rom[1259]=12'd469; hs_rom[1260]=12'd475; hs_rom[1261]=12'd481; hs_rom[1262]=12'd487; hs_rom[1263]=12'd494;
    hs_rom[1264]=12'd501; hs_rom[1265]=12'd508; hs_rom[1266]=12'd516; hs_rom[1267]=12'd524; hs_rom[1268]=12'd533; hs_rom[1269]=12'd543; hs_rom[1270]=12'd554; hs_rom[1271]=12'd565;
    hs_rom[1272]=12'd578; hs_rom[1273]=12'd593; hs_rom[1274]=12'd611; hs_rom[1275]=12'd631; hs_rom[1276]=12'd657; hs_rom[1277]=12'd691; hs_rom[1278]=12'd741; hs_rom[1279]=12'd847;
    hs_rom[1280]=12'd2; hs_rom[1281]=12'd5; hs_rom[1282]=12'd7; hs_rom[1283]=12'd9; hs_rom[1284]=12'd11; hs_rom[1285]=12'd13; hs_rom[1286]=12'd14; hs_rom[1287]=12'd16;
    hs_rom[1288]=12'd18; hs_rom[1289]=12'd19; hs_rom[1290]=12'd21; hs_rom[1291]=12'd22; hs_rom[1292]=12'd24; hs_rom[1293]=12'd25; hs_rom[1294]=12'd27; hs_rom[1295]=12'd28;
    hs_rom[1296]=12'd30; hs_rom[1297]=12'd31; hs_rom[1298]=12'd33; hs_rom[1299]=12'd34; hs_rom[1300]=12'd36; hs_rom[1301]=12'd37; hs_rom[1302]=12'd38; hs_rom[1303]=12'd40;
    hs_rom[1304]=12'd41; hs_rom[1305]=12'd43; hs_rom[1306]=12'd44; hs_rom[1307]=12'd45; hs_rom[1308]=12'd47; hs_rom[1309]=12'd48; hs_rom[1310]=12'd49; hs_rom[1311]=12'd51;
    hs_rom[1312]=12'd52; hs_rom[1313]=12'd54; hs_rom[1314]=12'd55; hs_rom[1315]=12'd56; hs_rom[1316]=12'd58; hs_rom[1317]=12'd59; hs_rom[1318]=12'd60; hs_rom[1319]=12'd62;
    hs_rom[1320]=12'd63; hs_rom[1321]=12'd64; hs_rom[1322]=12'd66; hs_rom[1323]=12'd67; hs_rom[1324]=12'd68; hs_rom[1325]=12'd70; hs_rom[1326]=12'd71; hs_rom[1327]=12'd72;
    hs_rom[1328]=12'd74; hs_rom[1329]=12'd75; hs_rom[1330]=12'd77; hs_rom[1331]=12'd78; hs_rom[1332]=12'd79; hs_rom[1333]=12'd81; hs_rom[1334]=12'd82; hs_rom[1335]=12'd83;
    hs_rom[1336]=12'd85; hs_rom[1337]=12'd86; hs_rom[1338]=12'd87; hs_rom[1339]=12'd89; hs_rom[1340]=12'd90; hs_rom[1341]=12'd92; hs_rom[1342]=12'd93; hs_rom[1343]=12'd94;
    hs_rom[1344]=12'd96; hs_rom[1345]=12'd97; hs_rom[1346]=12'd98; hs_rom[1347]=12'd100; hs_rom[1348]=12'd101; hs_rom[1349]=12'd103; hs_rom[1350]=12'd104; hs_rom[1351]=12'd106;
    hs_rom[1352]=12'd107; hs_rom[1353]=12'd108; hs_rom[1354]=12'd110; hs_rom[1355]=12'd111; hs_rom[1356]=12'd113; hs_rom[1357]=12'd114; hs_rom[1358]=12'd116; hs_rom[1359]=12'd117;
    hs_rom[1360]=12'd118; hs_rom[1361]=12'd120; hs_rom[1362]=12'd121; hs_rom[1363]=12'd123; hs_rom[1364]=12'd124; hs_rom[1365]=12'd126; hs_rom[1366]=12'd127; hs_rom[1367]=12'd129;
    hs_rom[1368]=12'd130; hs_rom[1369]=12'd132; hs_rom[1370]=12'd133; hs_rom[1371]=12'd135; hs_rom[1372]=12'd136; hs_rom[1373]=12'd138; hs_rom[1374]=12'd139; hs_rom[1375]=12'd141;
    hs_rom[1376]=12'd143; hs_rom[1377]=12'd144; hs_rom[1378]=12'd146; hs_rom[1379]=12'd147; hs_rom[1380]=12'd149; hs_rom[1381]=12'd150; hs_rom[1382]=12'd152; hs_rom[1383]=12'd154;
    hs_rom[1384]=12'd155; hs_rom[1385]=12'd157; hs_rom[1386]=12'd158; hs_rom[1387]=12'd160; hs_rom[1388]=12'd162; hs_rom[1389]=12'd163; hs_rom[1390]=12'd165; hs_rom[1391]=12'd167;
    hs_rom[1392]=12'd168; hs_rom[1393]=12'd170; hs_rom[1394]=12'd172; hs_rom[1395]=12'd173; hs_rom[1396]=12'd175; hs_rom[1397]=12'd177; hs_rom[1398]=12'd179; hs_rom[1399]=12'd180;
    hs_rom[1400]=12'd182; hs_rom[1401]=12'd184; hs_rom[1402]=12'd186; hs_rom[1403]=12'd187; hs_rom[1404]=12'd189; hs_rom[1405]=12'd191; hs_rom[1406]=12'd193; hs_rom[1407]=12'd195;
    hs_rom[1408]=12'd197; hs_rom[1409]=12'd198; hs_rom[1410]=12'd200; hs_rom[1411]=12'd202; hs_rom[1412]=12'd204; hs_rom[1413]=12'd206; hs_rom[1414]=12'd208; hs_rom[1415]=12'd210;
    hs_rom[1416]=12'd212; hs_rom[1417]=12'd214; hs_rom[1418]=12'd216; hs_rom[1419]=12'd218; hs_rom[1420]=12'd220; hs_rom[1421]=12'd222; hs_rom[1422]=12'd224; hs_rom[1423]=12'd226;
    hs_rom[1424]=12'd228; hs_rom[1425]=12'd230; hs_rom[1426]=12'd232; hs_rom[1427]=12'd234; hs_rom[1428]=12'd236; hs_rom[1429]=12'd238; hs_rom[1430]=12'd241; hs_rom[1431]=12'd243;
    hs_rom[1432]=12'd245; hs_rom[1433]=12'd247; hs_rom[1434]=12'd249; hs_rom[1435]=12'd252; hs_rom[1436]=12'd254; hs_rom[1437]=12'd256; hs_rom[1438]=12'd259; hs_rom[1439]=12'd261;
    hs_rom[1440]=12'd263; hs_rom[1441]=12'd266; hs_rom[1442]=12'd268; hs_rom[1443]=12'd270; hs_rom[1444]=12'd273; hs_rom[1445]=12'd275; hs_rom[1446]=12'd278; hs_rom[1447]=12'd280;
    hs_rom[1448]=12'd283; hs_rom[1449]=12'd286; hs_rom[1450]=12'd288; hs_rom[1451]=12'd291; hs_rom[1452]=12'd294; hs_rom[1453]=12'd296; hs_rom[1454]=12'd299; hs_rom[1455]=12'd302;
    hs_rom[1456]=12'd304; hs_rom[1457]=12'd307; hs_rom[1458]=12'd310; hs_rom[1459]=12'd313; hs_rom[1460]=12'd316; hs_rom[1461]=12'd319; hs_rom[1462]=12'd322; hs_rom[1463]=12'd325;
    hs_rom[1464]=12'd328; hs_rom[1465]=12'd331; hs_rom[1466]=12'd334; hs_rom[1467]=12'd337; hs_rom[1468]=12'd341; hs_rom[1469]=12'd344; hs_rom[1470]=12'd347; hs_rom[1471]=12'd351;
    hs_rom[1472]=12'd354; hs_rom[1473]=12'd358; hs_rom[1474]=12'd361; hs_rom[1475]=12'd365; hs_rom[1476]=12'd368; hs_rom[1477]=12'd372; hs_rom[1478]=12'd376; hs_rom[1479]=12'd380;
    hs_rom[1480]=12'd384; hs_rom[1481]=12'd388; hs_rom[1482]=12'd392; hs_rom[1483]=12'd396; hs_rom[1484]=12'd400; hs_rom[1485]=12'd404; hs_rom[1486]=12'd408; hs_rom[1487]=12'd413;
    hs_rom[1488]=12'd417; hs_rom[1489]=12'd422; hs_rom[1490]=12'd427; hs_rom[1491]=12'd431; hs_rom[1492]=12'd436; hs_rom[1493]=12'd441; hs_rom[1494]=12'd446; hs_rom[1495]=12'd452;
    hs_rom[1496]=12'd457; hs_rom[1497]=12'd462; hs_rom[1498]=12'd468; hs_rom[1499]=12'd474; hs_rom[1500]=12'd480; hs_rom[1501]=12'd486; hs_rom[1502]=12'd492; hs_rom[1503]=12'd499;
    hs_rom[1504]=12'd505; hs_rom[1505]=12'd512; hs_rom[1506]=12'd519; hs_rom[1507]=12'd526; hs_rom[1508]=12'd534; hs_rom[1509]=12'd542; hs_rom[1510]=12'd550; hs_rom[1511]=12'd558;
    hs_rom[1512]=12'd567; hs_rom[1513]=12'd576; hs_rom[1514]=12'd586; hs_rom[1515]=12'd596; hs_rom[1516]=12'd606; hs_rom[1517]=12'd617; hs_rom[1518]=12'd629; hs_rom[1519]=12'd641;
    hs_rom[1520]=12'd654; hs_rom[1521]=12'd668; hs_rom[1522]=12'd683; hs_rom[1523]=12'd699; hs_rom[1524]=12'd716; hs_rom[1525]=12'd735; hs_rom[1526]=12'd756; hs_rom[1527]=12'd778;
    hs_rom[1528]=12'd804; hs_rom[1529]=12'd834; hs_rom[1530]=12'd868; hs_rom[1531]=12'd909; hs_rom[1532]=12'd960; hs_rom[1533]=12'd1028; hs_rom[1534]=12'd1132; hs_rom[1535]=12'd1353;
    hs_rom[1536]=12'd0; hs_rom[1537]=12'd0; hs_rom[1538]=12'd0; hs_rom[1539]=12'd0; hs_rom[1540]=12'd0; hs_rom[1541]=12'd0; hs_rom[1542]=12'd1; hs_rom[1543]=12'd1;
    hs_rom[1544]=12'd1; hs_rom[1545]=12'd1; hs_rom[1546]=12'd1; hs_rom[1547]=12'd1; hs_rom[1548]=12'd2; hs_rom[1549]=12'd2; hs_rom[1550]=12'd2; hs_rom[1551]=12'd2;
    hs_rom[1552]=12'd3; hs_rom[1553]=12'd3; hs_rom[1554]=12'd3; hs_rom[1555]=12'd4; hs_rom[1556]=12'd4; hs_rom[1557]=12'd4; hs_rom[1558]=12'd5; hs_rom[1559]=12'd5;
    hs_rom[1560]=12'd6; hs_rom[1561]=12'd6; hs_rom[1562]=12'd6; hs_rom[1563]=12'd7; hs_rom[1564]=12'd7; hs_rom[1565]=12'd8; hs_rom[1566]=12'd8; hs_rom[1567]=12'd9;
    hs_rom[1568]=12'd9; hs_rom[1569]=12'd10; hs_rom[1570]=12'd10; hs_rom[1571]=12'd11; hs_rom[1572]=12'd11; hs_rom[1573]=12'd12; hs_rom[1574]=12'd13; hs_rom[1575]=12'd13;
    hs_rom[1576]=12'd14; hs_rom[1577]=12'd14; hs_rom[1578]=12'd15; hs_rom[1579]=12'd16; hs_rom[1580]=12'd16; hs_rom[1581]=12'd17; hs_rom[1582]=12'd18; hs_rom[1583]=12'd18;
    hs_rom[1584]=12'd19; hs_rom[1585]=12'd20; hs_rom[1586]=12'd21; hs_rom[1587]=12'd21; hs_rom[1588]=12'd22; hs_rom[1589]=12'd23; hs_rom[1590]=12'd24; hs_rom[1591]=12'd25;
    hs_rom[1592]=12'd25; hs_rom[1593]=12'd26; hs_rom[1594]=12'd27; hs_rom[1595]=12'd28; hs_rom[1596]=12'd29; hs_rom[1597]=12'd30; hs_rom[1598]=12'd31; hs_rom[1599]=12'd32;
    hs_rom[1600]=12'd33; hs_rom[1601]=12'd34; hs_rom[1602]=12'd35; hs_rom[1603]=12'd36; hs_rom[1604]=12'd37; hs_rom[1605]=12'd38; hs_rom[1606]=12'd39; hs_rom[1607]=12'd40;
    hs_rom[1608]=12'd41; hs_rom[1609]=12'd42; hs_rom[1610]=12'd43; hs_rom[1611]=12'd44; hs_rom[1612]=12'd45; hs_rom[1613]=12'd46; hs_rom[1614]=12'd47; hs_rom[1615]=12'd49;
    hs_rom[1616]=12'd50; hs_rom[1617]=12'd51; hs_rom[1618]=12'd52; hs_rom[1619]=12'd53; hs_rom[1620]=12'd55; hs_rom[1621]=12'd56; hs_rom[1622]=12'd57; hs_rom[1623]=12'd59;
    hs_rom[1624]=12'd60; hs_rom[1625]=12'd61; hs_rom[1626]=12'd63; hs_rom[1627]=12'd64; hs_rom[1628]=12'd65; hs_rom[1629]=12'd67; hs_rom[1630]=12'd68; hs_rom[1631]=12'd70;
    hs_rom[1632]=12'd71; hs_rom[1633]=12'd72; hs_rom[1634]=12'd74; hs_rom[1635]=12'd75; hs_rom[1636]=12'd77; hs_rom[1637]=12'd79; hs_rom[1638]=12'd80; hs_rom[1639]=12'd82;
    hs_rom[1640]=12'd83; hs_rom[1641]=12'd85; hs_rom[1642]=12'd87; hs_rom[1643]=12'd88; hs_rom[1644]=12'd90; hs_rom[1645]=12'd92; hs_rom[1646]=12'd93; hs_rom[1647]=12'd95;
    hs_rom[1648]=12'd97; hs_rom[1649]=12'd99; hs_rom[1650]=12'd100; hs_rom[1651]=12'd102; hs_rom[1652]=12'd104; hs_rom[1653]=12'd106; hs_rom[1654]=12'd108; hs_rom[1655]=12'd110;
    hs_rom[1656]=12'd112; hs_rom[1657]=12'd114; hs_rom[1658]=12'd116; hs_rom[1659]=12'd118; hs_rom[1660]=12'd120; hs_rom[1661]=12'd122; hs_rom[1662]=12'd124; hs_rom[1663]=12'd126;
    hs_rom[1664]=12'd128; hs_rom[1665]=12'd130; hs_rom[1666]=12'd133; hs_rom[1667]=12'd135; hs_rom[1668]=12'd137; hs_rom[1669]=12'd139; hs_rom[1670]=12'd142; hs_rom[1671]=12'd144;
    hs_rom[1672]=12'd146; hs_rom[1673]=12'd149; hs_rom[1674]=12'd151; hs_rom[1675]=12'd154; hs_rom[1676]=12'd156; hs_rom[1677]=12'd159; hs_rom[1678]=12'd161; hs_rom[1679]=12'd164;
    hs_rom[1680]=12'd166; hs_rom[1681]=12'd169; hs_rom[1682]=12'd172; hs_rom[1683]=12'd174; hs_rom[1684]=12'd177; hs_rom[1685]=12'd180; hs_rom[1686]=12'd183; hs_rom[1687]=12'd186;
    hs_rom[1688]=12'd188; hs_rom[1689]=12'd191; hs_rom[1690]=12'd194; hs_rom[1691]=12'd197; hs_rom[1692]=12'd200; hs_rom[1693]=12'd204; hs_rom[1694]=12'd207; hs_rom[1695]=12'd210;
    hs_rom[1696]=12'd213; hs_rom[1697]=12'd216; hs_rom[1698]=12'd220; hs_rom[1699]=12'd223; hs_rom[1700]=12'd226; hs_rom[1701]=12'd230; hs_rom[1702]=12'd233; hs_rom[1703]=12'd237;
    hs_rom[1704]=12'd241; hs_rom[1705]=12'd244; hs_rom[1706]=12'd248; hs_rom[1707]=12'd252; hs_rom[1708]=12'd256; hs_rom[1709]=12'd260; hs_rom[1710]=12'd263; hs_rom[1711]=12'd267;
    hs_rom[1712]=12'd272; hs_rom[1713]=12'd276; hs_rom[1714]=12'd280; hs_rom[1715]=12'd284; hs_rom[1716]=12'd288; hs_rom[1717]=12'd293; hs_rom[1718]=12'd297; hs_rom[1719]=12'd302;
    hs_rom[1720]=12'd307; hs_rom[1721]=12'd311; hs_rom[1722]=12'd316; hs_rom[1723]=12'd321; hs_rom[1724]=12'd326; hs_rom[1725]=12'd331; hs_rom[1726]=12'd336; hs_rom[1727]=12'd341;
    hs_rom[1728]=12'd347; hs_rom[1729]=12'd352; hs_rom[1730]=12'd358; hs_rom[1731]=12'd363; hs_rom[1732]=12'd369; hs_rom[1733]=12'd375; hs_rom[1734]=12'd381; hs_rom[1735]=12'd387;
    hs_rom[1736]=12'd393; hs_rom[1737]=12'd400; hs_rom[1738]=12'd406; hs_rom[1739]=12'd413; hs_rom[1740]=12'd420; hs_rom[1741]=12'd427; hs_rom[1742]=12'd434; hs_rom[1743]=12'd441;
    hs_rom[1744]=12'd448; hs_rom[1745]=12'd456; hs_rom[1746]=12'd464; hs_rom[1747]=12'd472; hs_rom[1748]=12'd480; hs_rom[1749]=12'd489; hs_rom[1750]=12'd497; hs_rom[1751]=12'd506;
    hs_rom[1752]=12'd515; hs_rom[1753]=12'd525; hs_rom[1754]=12'd534; hs_rom[1755]=12'd544; hs_rom[1756]=12'd554; hs_rom[1757]=12'd565; hs_rom[1758]=12'd576; hs_rom[1759]=12'd587;
    hs_rom[1760]=12'd599; hs_rom[1761]=12'd611; hs_rom[1762]=12'd624; hs_rom[1763]=12'd637; hs_rom[1764]=12'd650; hs_rom[1765]=12'd664; hs_rom[1766]=12'd679; hs_rom[1767]=12'd694;
    hs_rom[1768]=12'd710; hs_rom[1769]=12'd727; hs_rom[1770]=12'd744; hs_rom[1771]=12'd762; hs_rom[1772]=12'd782; hs_rom[1773]=12'd802; hs_rom[1774]=12'd824; hs_rom[1775]=12'd847;
    hs_rom[1776]=12'd871; hs_rom[1777]=12'd898; hs_rom[1778]=12'd926; hs_rom[1779]=12'd956; hs_rom[1780]=12'd990; hs_rom[1781]=12'd1026; hs_rom[1782]=12'd1066; hs_rom[1783]=12'd1111;
    hs_rom[1784]=12'd1161; hs_rom[1785]=12'd1220; hs_rom[1786]=12'd1288; hs_rom[1787]=12'd1370; hs_rom[1788]=12'd1474; hs_rom[1789]=12'd1614; hs_rom[1790]=12'd1828; hs_rom[1791]=12'd2295;
    hs_rom[1792]=12'd0; hs_rom[1793]=12'd0; hs_rom[1794]=12'd0; hs_rom[1795]=12'd0; hs_rom[1796]=12'd0; hs_rom[1797]=12'd0; hs_rom[1798]=12'd0; hs_rom[1799]=12'd0;
    hs_rom[1800]=12'd0; hs_rom[1801]=12'd0; hs_rom[1802]=12'd0; hs_rom[1803]=12'd0; hs_rom[1804]=12'd0; hs_rom[1805]=12'd0; hs_rom[1806]=12'd0; hs_rom[1807]=12'd0;
    hs_rom[1808]=12'd0; hs_rom[1809]=12'd0; hs_rom[1810]=12'd0; hs_rom[1811]=12'd0; hs_rom[1812]=12'd0; hs_rom[1813]=12'd0; hs_rom[1814]=12'd0; hs_rom[1815]=12'd0;
    hs_rom[1816]=12'd0; hs_rom[1817]=12'd0; hs_rom[1818]=12'd0; hs_rom[1819]=12'd0; hs_rom[1820]=12'd0; hs_rom[1821]=12'd0; hs_rom[1822]=12'd0; hs_rom[1823]=12'd0;
    hs_rom[1824]=12'd0; hs_rom[1825]=12'd0; hs_rom[1826]=12'd0; hs_rom[1827]=12'd0; hs_rom[1828]=12'd0; hs_rom[1829]=12'd0; hs_rom[1830]=12'd0; hs_rom[1831]=12'd0;
    hs_rom[1832]=12'd0; hs_rom[1833]=12'd0; hs_rom[1834]=12'd0; hs_rom[1835]=12'd0; hs_rom[1836]=12'd0; hs_rom[1837]=12'd0; hs_rom[1838]=12'd0; hs_rom[1839]=12'd0;
    hs_rom[1840]=12'd0; hs_rom[1841]=12'd0; hs_rom[1842]=12'd1; hs_rom[1843]=12'd1; hs_rom[1844]=12'd1; hs_rom[1845]=12'd1; hs_rom[1846]=12'd1; hs_rom[1847]=12'd1;
    hs_rom[1848]=12'd1; hs_rom[1849]=12'd1; hs_rom[1850]=12'd1; hs_rom[1851]=12'd1; hs_rom[1852]=12'd1; hs_rom[1853]=12'd1; hs_rom[1854]=12'd1; hs_rom[1855]=12'd1;
    hs_rom[1856]=12'd2; hs_rom[1857]=12'd2; hs_rom[1858]=12'd2; hs_rom[1859]=12'd2; hs_rom[1860]=12'd2; hs_rom[1861]=12'd2; hs_rom[1862]=12'd2; hs_rom[1863]=12'd2;
    hs_rom[1864]=12'd3; hs_rom[1865]=12'd3; hs_rom[1866]=12'd3; hs_rom[1867]=12'd3; hs_rom[1868]=12'd3; hs_rom[1869]=12'd4; hs_rom[1870]=12'd4; hs_rom[1871]=12'd4;
    hs_rom[1872]=12'd4; hs_rom[1873]=12'd4; hs_rom[1874]=12'd5; hs_rom[1875]=12'd5; hs_rom[1876]=12'd5; hs_rom[1877]=12'd6; hs_rom[1878]=12'd6; hs_rom[1879]=12'd6;
    hs_rom[1880]=12'd6; hs_rom[1881]=12'd7; hs_rom[1882]=12'd7; hs_rom[1883]=12'd7; hs_rom[1884]=12'd8; hs_rom[1885]=12'd8; hs_rom[1886]=12'd9; hs_rom[1887]=12'd9;
    hs_rom[1888]=12'd10; hs_rom[1889]=12'd10; hs_rom[1890]=12'd10; hs_rom[1891]=12'd11; hs_rom[1892]=12'd11; hs_rom[1893]=12'd12; hs_rom[1894]=12'd13; hs_rom[1895]=12'd13;
    hs_rom[1896]=12'd14; hs_rom[1897]=12'd14; hs_rom[1898]=12'd15; hs_rom[1899]=12'd16; hs_rom[1900]=12'd16; hs_rom[1901]=12'd17; hs_rom[1902]=12'd18; hs_rom[1903]=12'd18;
    hs_rom[1904]=12'd19; hs_rom[1905]=12'd20; hs_rom[1906]=12'd21; hs_rom[1907]=12'd22; hs_rom[1908]=12'd22; hs_rom[1909]=12'd23; hs_rom[1910]=12'd24; hs_rom[1911]=12'd25;
    hs_rom[1912]=12'd26; hs_rom[1913]=12'd27; hs_rom[1914]=12'd28; hs_rom[1915]=12'd29; hs_rom[1916]=12'd30; hs_rom[1917]=12'd32; hs_rom[1918]=12'd33; hs_rom[1919]=12'd34;
    hs_rom[1920]=12'd35; hs_rom[1921]=12'd36; hs_rom[1922]=12'd38; hs_rom[1923]=12'd39; hs_rom[1924]=12'd41; hs_rom[1925]=12'd42; hs_rom[1926]=12'd43; hs_rom[1927]=12'd45;
    hs_rom[1928]=12'd47; hs_rom[1929]=12'd48; hs_rom[1930]=12'd50; hs_rom[1931]=12'd52; hs_rom[1932]=12'd53; hs_rom[1933]=12'd55; hs_rom[1934]=12'd57; hs_rom[1935]=12'd59;
    hs_rom[1936]=12'd61; hs_rom[1937]=12'd63; hs_rom[1938]=12'd65; hs_rom[1939]=12'd67; hs_rom[1940]=12'd69; hs_rom[1941]=12'd71; hs_rom[1942]=12'd74; hs_rom[1943]=12'd76;
    hs_rom[1944]=12'd78; hs_rom[1945]=12'd81; hs_rom[1946]=12'd83; hs_rom[1947]=12'd86; hs_rom[1948]=12'd89; hs_rom[1949]=12'd91; hs_rom[1950]=12'd94; hs_rom[1951]=12'd97;
    hs_rom[1952]=12'd100; hs_rom[1953]=12'd103; hs_rom[1954]=12'd106; hs_rom[1955]=12'd110; hs_rom[1956]=12'd113; hs_rom[1957]=12'd116; hs_rom[1958]=12'd120; hs_rom[1959]=12'd123;
    hs_rom[1960]=12'd127; hs_rom[1961]=12'd131; hs_rom[1962]=12'd135; hs_rom[1963]=12'd139; hs_rom[1964]=12'd143; hs_rom[1965]=12'd147; hs_rom[1966]=12'd151; hs_rom[1967]=12'd155;
    hs_rom[1968]=12'd160; hs_rom[1969]=12'd165; hs_rom[1970]=12'd169; hs_rom[1971]=12'd174; hs_rom[1972]=12'd179; hs_rom[1973]=12'd184; hs_rom[1974]=12'd190; hs_rom[1975]=12'd195;
    hs_rom[1976]=12'd201; hs_rom[1977]=12'd206; hs_rom[1978]=12'd212; hs_rom[1979]=12'd218; hs_rom[1980]=12'd225; hs_rom[1981]=12'd231; hs_rom[1982]=12'd237; hs_rom[1983]=12'd244;
    hs_rom[1984]=12'd251; hs_rom[1985]=12'd258; hs_rom[1986]=12'd266; hs_rom[1987]=12'd273; hs_rom[1988]=12'd281; hs_rom[1989]=12'd289; hs_rom[1990]=12'd297; hs_rom[1991]=12'd306;
    hs_rom[1992]=12'd314; hs_rom[1993]=12'd323; hs_rom[1994]=12'd333; hs_rom[1995]=12'd342; hs_rom[1996]=12'd352; hs_rom[1997]=12'd362; hs_rom[1998]=12'd372; hs_rom[1999]=12'd383;
    hs_rom[2000]=12'd394; hs_rom[2001]=12'd406; hs_rom[2002]=12'd418; hs_rom[2003]=12'd430; hs_rom[2004]=12'd443; hs_rom[2005]=12'd456; hs_rom[2006]=12'd469; hs_rom[2007]=12'd483;
    hs_rom[2008]=12'd498; hs_rom[2009]=12'd513; hs_rom[2010]=12'd529; hs_rom[2011]=12'd545; hs_rom[2012]=12'd562; hs_rom[2013]=12'd579; hs_rom[2014]=12'd598; hs_rom[2015]=12'd617;
    hs_rom[2016]=12'd637; hs_rom[2017]=12'd657; hs_rom[2018]=12'd679; hs_rom[2019]=12'd701; hs_rom[2020]=12'd725; hs_rom[2021]=12'd750; hs_rom[2022]=12'd776; hs_rom[2023]=12'd803;
    hs_rom[2024]=12'd832; hs_rom[2025]=12'd862; hs_rom[2026]=12'd894; hs_rom[2027]=12'd928; hs_rom[2028]=12'd964; hs_rom[2029]=12'd1003; hs_rom[2030]=12'd1044; hs_rom[2031]=12'd1087;
    hs_rom[2032]=12'd1135; hs_rom[2033]=12'd1185; hs_rom[2034]=12'd1241; hs_rom[2035]=12'd1301; hs_rom[2036]=12'd1367; hs_rom[2037]=12'd1439; hs_rom[2038]=12'd1520; hs_rom[2039]=12'd1612;
    hs_rom[2040]=12'd1716; hs_rom[2041]=12'd1837; hs_rom[2042]=12'd1980; hs_rom[2043]=12'd2155; hs_rom[2044]=12'd2377; hs_rom[2045]=12'd2682; hs_rom[2046]=12'd3155; hs_rom[2047]=12'd4095;
end

// ho_rom  : address = {eff_level[2:0], addr[7:0]}  (6×256)
reg [11:0] ho_rom [0:1535];
initial begin
    ho_rom[0]=12'd256; ho_rom[1]=12'd256; ho_rom[2]=12'd256; ho_rom[3]=12'd256; ho_rom[4]=12'd256; ho_rom[5]=12'd256; ho_rom[6]=12'd256; ho_rom[7]=12'd256;
    ho_rom[8]=12'd256; ho_rom[9]=12'd256; ho_rom[10]=12'd256; ho_rom[11]=12'd256; ho_rom[12]=12'd256; ho_rom[13]=12'd256; ho_rom[14]=12'd256; ho_rom[15]=12'd256;
    ho_rom[16]=12'd256; ho_rom[17]=12'd256; ho_rom[18]=12'd256; ho_rom[19]=12'd256; ho_rom[20]=12'd256; ho_rom[21]=12'd256; ho_rom[22]=12'd256; ho_rom[23]=12'd256;
    ho_rom[24]=12'd256; ho_rom[25]=12'd256; ho_rom[26]=12'd256; ho_rom[27]=12'd256; ho_rom[28]=12'd256; ho_rom[29]=12'd256; ho_rom[30]=12'd256; ho_rom[31]=12'd256;
    ho_rom[32]=12'd256; ho_rom[33]=12'd256; ho_rom[34]=12'd256; ho_rom[35]=12'd256; ho_rom[36]=12'd256; ho_rom[37]=12'd256; ho_rom[38]=12'd256; ho_rom[39]=12'd256;
    ho_rom[40]=12'd256; ho_rom[41]=12'd256; ho_rom[42]=12'd256; ho_rom[43]=12'd256; ho_rom[44]=12'd256; ho_rom[45]=12'd256; ho_rom[46]=12'd256; ho_rom[47]=12'd256;
    ho_rom[48]=12'd256; ho_rom[49]=12'd256; ho_rom[50]=12'd256; ho_rom[51]=12'd256; ho_rom[52]=12'd256; ho_rom[53]=12'd256; ho_rom[54]=12'd256; ho_rom[55]=12'd256;
    ho_rom[56]=12'd256; ho_rom[57]=12'd256; ho_rom[58]=12'd256; ho_rom[59]=12'd256; ho_rom[60]=12'd256; ho_rom[61]=12'd256; ho_rom[62]=12'd256; ho_rom[63]=12'd256;
    ho_rom[64]=12'd256; ho_rom[65]=12'd256; ho_rom[66]=12'd256; ho_rom[67]=12'd256; ho_rom[68]=12'd256; ho_rom[69]=12'd256; ho_rom[70]=12'd256; ho_rom[71]=12'd256;
    ho_rom[72]=12'd256; ho_rom[73]=12'd256; ho_rom[74]=12'd256; ho_rom[75]=12'd256; ho_rom[76]=12'd256; ho_rom[77]=12'd256; ho_rom[78]=12'd256; ho_rom[79]=12'd256;
    ho_rom[80]=12'd256; ho_rom[81]=12'd256; ho_rom[82]=12'd256; ho_rom[83]=12'd256; ho_rom[84]=12'd256; ho_rom[85]=12'd256; ho_rom[86]=12'd256; ho_rom[87]=12'd256;
    ho_rom[88]=12'd256; ho_rom[89]=12'd256; ho_rom[90]=12'd256; ho_rom[91]=12'd256; ho_rom[92]=12'd256; ho_rom[93]=12'd256; ho_rom[94]=12'd256; ho_rom[95]=12'd256;
    ho_rom[96]=12'd256; ho_rom[97]=12'd256; ho_rom[98]=12'd256; ho_rom[99]=12'd256; ho_rom[100]=12'd256; ho_rom[101]=12'd256; ho_rom[102]=12'd256; ho_rom[103]=12'd256;
    ho_rom[104]=12'd256; ho_rom[105]=12'd256; ho_rom[106]=12'd256; ho_rom[107]=12'd256; ho_rom[108]=12'd256; ho_rom[109]=12'd256; ho_rom[110]=12'd256; ho_rom[111]=12'd256;
    ho_rom[112]=12'd256; ho_rom[113]=12'd256; ho_rom[114]=12'd256; ho_rom[115]=12'd256; ho_rom[116]=12'd256; ho_rom[117]=12'd256; ho_rom[118]=12'd256; ho_rom[119]=12'd256;
    ho_rom[120]=12'd256; ho_rom[121]=12'd256; ho_rom[122]=12'd256; ho_rom[123]=12'd256; ho_rom[124]=12'd256; ho_rom[125]=12'd256; ho_rom[126]=12'd256; ho_rom[127]=12'd256;
    ho_rom[128]=12'd256; ho_rom[129]=12'd256; ho_rom[130]=12'd256; ho_rom[131]=12'd256; ho_rom[132]=12'd256; ho_rom[133]=12'd256; ho_rom[134]=12'd256; ho_rom[135]=12'd256;
    ho_rom[136]=12'd256; ho_rom[137]=12'd256; ho_rom[138]=12'd256; ho_rom[139]=12'd256; ho_rom[140]=12'd256; ho_rom[141]=12'd256; ho_rom[142]=12'd256; ho_rom[143]=12'd256;
    ho_rom[144]=12'd256; ho_rom[145]=12'd256; ho_rom[146]=12'd256; ho_rom[147]=12'd256; ho_rom[148]=12'd256; ho_rom[149]=12'd256; ho_rom[150]=12'd256; ho_rom[151]=12'd256;
    ho_rom[152]=12'd256; ho_rom[153]=12'd256; ho_rom[154]=12'd256; ho_rom[155]=12'd256; ho_rom[156]=12'd256; ho_rom[157]=12'd256; ho_rom[158]=12'd256; ho_rom[159]=12'd256;
    ho_rom[160]=12'd256; ho_rom[161]=12'd256; ho_rom[162]=12'd256; ho_rom[163]=12'd256; ho_rom[164]=12'd256; ho_rom[165]=12'd256; ho_rom[166]=12'd256; ho_rom[167]=12'd256;
    ho_rom[168]=12'd256; ho_rom[169]=12'd256; ho_rom[170]=12'd256; ho_rom[171]=12'd256; ho_rom[172]=12'd256; ho_rom[173]=12'd256; ho_rom[174]=12'd256; ho_rom[175]=12'd256;
    ho_rom[176]=12'd256; ho_rom[177]=12'd256; ho_rom[178]=12'd256; ho_rom[179]=12'd256; ho_rom[180]=12'd256; ho_rom[181]=12'd256; ho_rom[182]=12'd256; ho_rom[183]=12'd256;
    ho_rom[184]=12'd256; ho_rom[185]=12'd256; ho_rom[186]=12'd256; ho_rom[187]=12'd256; ho_rom[188]=12'd256; ho_rom[189]=12'd256; ho_rom[190]=12'd256; ho_rom[191]=12'd256;
    ho_rom[192]=12'd256; ho_rom[193]=12'd256; ho_rom[194]=12'd256; ho_rom[195]=12'd256; ho_rom[196]=12'd256; ho_rom[197]=12'd256; ho_rom[198]=12'd256; ho_rom[199]=12'd256;
    ho_rom[200]=12'd256; ho_rom[201]=12'd256; ho_rom[202]=12'd256; ho_rom[203]=12'd256; ho_rom[204]=12'd256; ho_rom[205]=12'd256; ho_rom[206]=12'd256; ho_rom[207]=12'd256;
    ho_rom[208]=12'd256; ho_rom[209]=12'd256; ho_rom[210]=12'd256; ho_rom[211]=12'd256; ho_rom[212]=12'd256; ho_rom[213]=12'd256; ho_rom[214]=12'd256; ho_rom[215]=12'd256;
    ho_rom[216]=12'd256; ho_rom[217]=12'd256; ho_rom[218]=12'd256; ho_rom[219]=12'd256; ho_rom[220]=12'd256; ho_rom[221]=12'd256; ho_rom[222]=12'd256; ho_rom[223]=12'd256;
    ho_rom[224]=12'd256; ho_rom[225]=12'd256; ho_rom[226]=12'd256; ho_rom[227]=12'd256; ho_rom[228]=12'd256; ho_rom[229]=12'd256; ho_rom[230]=12'd256; ho_rom[231]=12'd256;
    ho_rom[232]=12'd256; ho_rom[233]=12'd256; ho_rom[234]=12'd256; ho_rom[235]=12'd256; ho_rom[236]=12'd256; ho_rom[237]=12'd256; ho_rom[238]=12'd256; ho_rom[239]=12'd256;
    ho_rom[240]=12'd256; ho_rom[241]=12'd256; ho_rom[242]=12'd256; ho_rom[243]=12'd256; ho_rom[244]=12'd256; ho_rom[245]=12'd256; ho_rom[246]=12'd256; ho_rom[247]=12'd256;
    ho_rom[248]=12'd256; ho_rom[249]=12'd256; ho_rom[250]=12'd256; ho_rom[251]=12'd256; ho_rom[252]=12'd256; ho_rom[253]=12'd256; ho_rom[254]=12'd256; ho_rom[255]=12'd256;
    ho_rom[256]=12'd169; ho_rom[257]=12'd178; ho_rom[258]=12'd182; ho_rom[259]=12'd186; ho_rom[260]=12'd188; ho_rom[261]=12'd191; ho_rom[262]=12'd193; ho_rom[263]=12'd194;
    ho_rom[264]=12'd196; ho_rom[265]=12'd197; ho_rom[266]=12'd198; ho_rom[267]=12'd200; ho_rom[268]=12'd201; ho_rom[269]=12'd202; ho_rom[270]=12'd203; ho_rom[271]=12'd204;
    ho_rom[272]=12'd205; ho_rom[273]=12'd206; ho_rom[274]=12'd206; ho_rom[275]=12'd207; ho_rom[276]=12'd208; ho_rom[277]=12'd209; ho_rom[278]=12'd210; ho_rom[279]=12'd210;
    ho_rom[280]=12'd211; ho_rom[281]=12'd212; ho_rom[282]=12'd212; ho_rom[283]=12'd213; ho_rom[284]=12'd214; ho_rom[285]=12'd214; ho_rom[286]=12'd215; ho_rom[287]=12'd215;
    ho_rom[288]=12'd216; ho_rom[289]=12'd216; ho_rom[290]=12'd217; ho_rom[291]=12'd218; ho_rom[292]=12'd218; ho_rom[293]=12'd219; ho_rom[294]=12'd219; ho_rom[295]=12'd220;
    ho_rom[296]=12'd220; ho_rom[297]=12'd221; ho_rom[298]=12'd221; ho_rom[299]=12'd222; ho_rom[300]=12'd222; ho_rom[301]=12'd223; ho_rom[302]=12'd223; ho_rom[303]=12'd223;
    ho_rom[304]=12'd224; ho_rom[305]=12'd224; ho_rom[306]=12'd225; ho_rom[307]=12'd225; ho_rom[308]=12'd226; ho_rom[309]=12'd226; ho_rom[310]=12'd227; ho_rom[311]=12'd227;
    ho_rom[312]=12'd227; ho_rom[313]=12'd228; ho_rom[314]=12'd228; ho_rom[315]=12'd229; ho_rom[316]=12'd229; ho_rom[317]=12'd230; ho_rom[318]=12'd230; ho_rom[319]=12'd230;
    ho_rom[320]=12'd231; ho_rom[321]=12'd231; ho_rom[322]=12'd232; ho_rom[323]=12'd232; ho_rom[324]=12'd232; ho_rom[325]=12'd233; ho_rom[326]=12'd233; ho_rom[327]=12'd233;
    ho_rom[328]=12'd234; ho_rom[329]=12'd234; ho_rom[330]=12'd235; ho_rom[331]=12'd235; ho_rom[332]=12'd235; ho_rom[333]=12'd236; ho_rom[334]=12'd236; ho_rom[335]=12'd236;
    ho_rom[336]=12'd237; ho_rom[337]=12'd237; ho_rom[338]=12'd238; ho_rom[339]=12'd238; ho_rom[340]=12'd238; ho_rom[341]=12'd239; ho_rom[342]=12'd239; ho_rom[343]=12'd239;
    ho_rom[344]=12'd240; ho_rom[345]=12'd240; ho_rom[346]=12'd240; ho_rom[347]=12'd241; ho_rom[348]=12'd241; ho_rom[349]=12'd241; ho_rom[350]=12'd242; ho_rom[351]=12'd242;
    ho_rom[352]=12'd243; ho_rom[353]=12'd243; ho_rom[354]=12'd243; ho_rom[355]=12'd244; ho_rom[356]=12'd244; ho_rom[357]=12'd244; ho_rom[358]=12'd245; ho_rom[359]=12'd245;
    ho_rom[360]=12'd245; ho_rom[361]=12'd246; ho_rom[362]=12'd246; ho_rom[363]=12'd246; ho_rom[364]=12'd247; ho_rom[365]=12'd247; ho_rom[366]=12'd247; ho_rom[367]=12'd248;
    ho_rom[368]=12'd248; ho_rom[369]=12'd248; ho_rom[370]=12'd249; ho_rom[371]=12'd249; ho_rom[372]=12'd249; ho_rom[373]=12'd250; ho_rom[374]=12'd250; ho_rom[375]=12'd251;
    ho_rom[376]=12'd251; ho_rom[377]=12'd251; ho_rom[378]=12'd252; ho_rom[379]=12'd252; ho_rom[380]=12'd252; ho_rom[381]=12'd253; ho_rom[382]=12'd253; ho_rom[383]=12'd253;
    ho_rom[384]=12'd254; ho_rom[385]=12'd254; ho_rom[386]=12'd254; ho_rom[387]=12'd255; ho_rom[388]=12'd255; ho_rom[389]=12'd255; ho_rom[390]=12'd256; ho_rom[391]=12'd256;
    ho_rom[392]=12'd256; ho_rom[393]=12'd257; ho_rom[394]=12'd257; ho_rom[395]=12'd258; ho_rom[396]=12'd258; ho_rom[397]=12'd258; ho_rom[398]=12'd259; ho_rom[399]=12'd259;
    ho_rom[400]=12'd259; ho_rom[401]=12'd260; ho_rom[402]=12'd260; ho_rom[403]=12'd260; ho_rom[404]=12'd261; ho_rom[405]=12'd261; ho_rom[406]=12'd262; ho_rom[407]=12'd262;
    ho_rom[408]=12'd262; ho_rom[409]=12'd263; ho_rom[410]=12'd263; ho_rom[411]=12'd263; ho_rom[412]=12'd264; ho_rom[413]=12'd264; ho_rom[414]=12'd265; ho_rom[415]=12'd265;
    ho_rom[416]=12'd265; ho_rom[417]=12'd266; ho_rom[418]=12'd266; ho_rom[419]=12'd266; ho_rom[420]=12'd267; ho_rom[421]=12'd267; ho_rom[422]=12'd268; ho_rom[423]=12'd268;
    ho_rom[424]=12'd268; ho_rom[425]=12'd269; ho_rom[426]=12'd269; ho_rom[427]=12'd270; ho_rom[428]=12'd270; ho_rom[429]=12'd270; ho_rom[430]=12'd271; ho_rom[431]=12'd271;
    ho_rom[432]=12'd272; ho_rom[433]=12'd272; ho_rom[434]=12'd273; ho_rom[435]=12'd273; ho_rom[436]=12'd273; ho_rom[437]=12'd274; ho_rom[438]=12'd274; ho_rom[439]=12'd275;
    ho_rom[440]=12'd275; ho_rom[441]=12'd276; ho_rom[442]=12'd276; ho_rom[443]=12'd277; ho_rom[444]=12'd277; ho_rom[445]=12'd278; ho_rom[446]=12'd278; ho_rom[447]=12'd278;
    ho_rom[448]=12'd279; ho_rom[449]=12'd279; ho_rom[450]=12'd280; ho_rom[451]=12'd280; ho_rom[452]=12'd281; ho_rom[453]=12'd281; ho_rom[454]=12'd282; ho_rom[455]=12'd282;
    ho_rom[456]=12'd283; ho_rom[457]=12'd284; ho_rom[458]=12'd284; ho_rom[459]=12'd285; ho_rom[460]=12'd285; ho_rom[461]=12'd286; ho_rom[462]=12'd286; ho_rom[463]=12'd287;
    ho_rom[464]=12'd287; ho_rom[465]=12'd288; ho_rom[466]=12'd289; ho_rom[467]=12'd289; ho_rom[468]=12'd290; ho_rom[469]=12'd291; ho_rom[470]=12'd291; ho_rom[471]=12'd292;
    ho_rom[472]=12'd293; ho_rom[473]=12'd293; ho_rom[474]=12'd294; ho_rom[475]=12'd295; ho_rom[476]=12'd295; ho_rom[477]=12'd296; ho_rom[478]=12'd297; ho_rom[479]=12'd298;
    ho_rom[480]=12'd298; ho_rom[481]=12'd299; ho_rom[482]=12'd300; ho_rom[483]=12'd301; ho_rom[484]=12'd302; ho_rom[485]=12'd303; ho_rom[486]=12'd304; ho_rom[487]=12'd305;
    ho_rom[488]=12'd306; ho_rom[489]=12'd307; ho_rom[490]=12'd308; ho_rom[491]=12'd309; ho_rom[492]=12'd310; ho_rom[493]=12'd311; ho_rom[494]=12'd313; ho_rom[495]=12'd314;
    ho_rom[496]=12'd315; ho_rom[497]=12'd317; ho_rom[498]=12'd318; ho_rom[499]=12'd320; ho_rom[500]=12'd322; ho_rom[501]=12'd324; ho_rom[502]=12'd326; ho_rom[503]=12'd328;
    ho_rom[504]=12'd331; ho_rom[505]=12'd334; ho_rom[506]=12'd337; ho_rom[507]=12'd341; ho_rom[508]=12'd346; ho_rom[509]=12'd352; ho_rom[510]=12'd361; ho_rom[511]=12'd380;
    ho_rom[512]=12'd111; ho_rom[513]=12'd122; ho_rom[514]=12'd129; ho_rom[515]=12'd134; ho_rom[516]=12'd137; ho_rom[517]=12'd140; ho_rom[518]=12'd143; ho_rom[519]=12'd146;
    ho_rom[520]=12'd148; ho_rom[521]=12'd150; ho_rom[522]=12'd152; ho_rom[523]=12'd154; ho_rom[524]=12'd156; ho_rom[525]=12'd157; ho_rom[526]=12'd159; ho_rom[527]=12'd160;
    ho_rom[528]=12'd162; ho_rom[529]=12'd163; ho_rom[530]=12'd164; ho_rom[531]=12'd166; ho_rom[532]=12'd167; ho_rom[533]=12'd168; ho_rom[534]=12'd169; ho_rom[535]=12'd170;
    ho_rom[536]=12'd171; ho_rom[537]=12'd173; ho_rom[538]=12'd174; ho_rom[539]=12'd175; ho_rom[540]=12'd176; ho_rom[541]=12'd177; ho_rom[542]=12'd178; ho_rom[543]=12'd179;
    ho_rom[544]=12'd179; ho_rom[545]=12'd180; ho_rom[546]=12'd181; ho_rom[547]=12'd182; ho_rom[548]=12'd183; ho_rom[549]=12'd184; ho_rom[550]=12'd185; ho_rom[551]=12'd186;
    ho_rom[552]=12'd187; ho_rom[553]=12'd187; ho_rom[554]=12'd188; ho_rom[555]=12'd189; ho_rom[556]=12'd190; ho_rom[557]=12'd191; ho_rom[558]=12'd191; ho_rom[559]=12'd192;
    ho_rom[560]=12'd193; ho_rom[561]=12'd194; ho_rom[562]=12'd195; ho_rom[563]=12'd195; ho_rom[564]=12'd196; ho_rom[565]=12'd197; ho_rom[566]=12'd197; ho_rom[567]=12'd198;
    ho_rom[568]=12'd199; ho_rom[569]=12'd200; ho_rom[570]=12'd200; ho_rom[571]=12'd201; ho_rom[572]=12'd202; ho_rom[573]=12'd203; ho_rom[574]=12'd203; ho_rom[575]=12'd204;
    ho_rom[576]=12'd205; ho_rom[577]=12'd205; ho_rom[578]=12'd206; ho_rom[579]=12'd207; ho_rom[580]=12'd207; ho_rom[581]=12'd208; ho_rom[582]=12'd209; ho_rom[583]=12'd209;
    ho_rom[584]=12'd210; ho_rom[585]=12'd211; ho_rom[586]=12'd211; ho_rom[587]=12'd212; ho_rom[588]=12'd213; ho_rom[589]=12'd213; ho_rom[590]=12'd214; ho_rom[591]=12'd215;
    ho_rom[592]=12'd215; ho_rom[593]=12'd216; ho_rom[594]=12'd217; ho_rom[595]=12'd217; ho_rom[596]=12'd218; ho_rom[597]=12'd219; ho_rom[598]=12'd219; ho_rom[599]=12'd220;
    ho_rom[600]=12'd221; ho_rom[601]=12'd221; ho_rom[602]=12'd222; ho_rom[603]=12'd223; ho_rom[604]=12'd223; ho_rom[605]=12'd224; ho_rom[606]=12'd225; ho_rom[607]=12'd225;
    ho_rom[608]=12'd226; ho_rom[609]=12'd226; ho_rom[610]=12'd227; ho_rom[611]=12'd228; ho_rom[612]=12'd228; ho_rom[613]=12'd229; ho_rom[614]=12'd230; ho_rom[615]=12'd230;
    ho_rom[616]=12'd231; ho_rom[617]=12'd232; ho_rom[618]=12'd232; ho_rom[619]=12'd233; ho_rom[620]=12'd234; ho_rom[621]=12'd234; ho_rom[622]=12'd235; ho_rom[623]=12'd235;
    ho_rom[624]=12'd236; ho_rom[625]=12'd237; ho_rom[626]=12'd237; ho_rom[627]=12'd238; ho_rom[628]=12'd239; ho_rom[629]=12'd239; ho_rom[630]=12'd240; ho_rom[631]=12'd241;
    ho_rom[632]=12'd241; ho_rom[633]=12'd242; ho_rom[634]=12'd243; ho_rom[635]=12'd243; ho_rom[636]=12'd244; ho_rom[637]=12'd245; ho_rom[638]=12'd245; ho_rom[639]=12'd246;
    ho_rom[640]=12'd247; ho_rom[641]=12'd247; ho_rom[642]=12'd248; ho_rom[643]=12'd249; ho_rom[644]=12'd249; ho_rom[645]=12'd250; ho_rom[646]=12'd251; ho_rom[647]=12'd251;
    ho_rom[648]=12'd252; ho_rom[649]=12'd253; ho_rom[650]=12'd253; ho_rom[651]=12'd254; ho_rom[652]=12'd255; ho_rom[653]=12'd256; ho_rom[654]=12'd256; ho_rom[655]=12'd257;
    ho_rom[656]=12'd258; ho_rom[657]=12'd258; ho_rom[658]=12'd259; ho_rom[659]=12'd260; ho_rom[660]=12'd261; ho_rom[661]=12'd261; ho_rom[662]=12'd262; ho_rom[663]=12'd263;
    ho_rom[664]=12'd263; ho_rom[665]=12'd264; ho_rom[666]=12'd265; ho_rom[667]=12'd266; ho_rom[668]=12'd266; ho_rom[669]=12'd267; ho_rom[670]=12'd268; ho_rom[671]=12'd269;
    ho_rom[672]=12'd269; ho_rom[673]=12'd270; ho_rom[674]=12'd271; ho_rom[675]=12'd272; ho_rom[676]=12'd273; ho_rom[677]=12'd273; ho_rom[678]=12'd274; ho_rom[679]=12'd275;
    ho_rom[680]=12'd276; ho_rom[681]=12'd277; ho_rom[682]=12'd277; ho_rom[683]=12'd278; ho_rom[684]=12'd279; ho_rom[685]=12'd280; ho_rom[686]=12'd281; ho_rom[687]=12'd282;
    ho_rom[688]=12'd283; ho_rom[689]=12'd283; ho_rom[690]=12'd284; ho_rom[691]=12'd285; ho_rom[692]=12'd286; ho_rom[693]=12'd287; ho_rom[694]=12'd288; ho_rom[695]=12'd289;
    ho_rom[696]=12'd290; ho_rom[697]=12'd291; ho_rom[698]=12'd292; ho_rom[699]=12'd293; ho_rom[700]=12'd294; ho_rom[701]=12'd295; ho_rom[702]=12'd296; ho_rom[703]=12'd297;
    ho_rom[704]=12'd298; ho_rom[705]=12'd299; ho_rom[706]=12'd300; ho_rom[707]=12'd301; ho_rom[708]=12'd302; ho_rom[709]=12'd303; ho_rom[710]=12'd304; ho_rom[711]=12'd305;
    ho_rom[712]=12'd306; ho_rom[713]=12'd307; ho_rom[714]=12'd308; ho_rom[715]=12'd310; ho_rom[716]=12'd311; ho_rom[717]=12'd312; ho_rom[718]=12'd313; ho_rom[719]=12'd314;
    ho_rom[720]=12'd316; ho_rom[721]=12'd317; ho_rom[722]=12'd318; ho_rom[723]=12'd320; ho_rom[724]=12'd321; ho_rom[725]=12'd322; ho_rom[726]=12'd324; ho_rom[727]=12'd325;
    ho_rom[728]=12'd327; ho_rom[729]=12'd328; ho_rom[730]=12'd330; ho_rom[731]=12'd331; ho_rom[732]=12'd333; ho_rom[733]=12'd335; ho_rom[734]=12'd336; ho_rom[735]=12'd338;
    ho_rom[736]=12'd340; ho_rom[737]=12'd342; ho_rom[738]=12'd344; ho_rom[739]=12'd346; ho_rom[740]=12'd348; ho_rom[741]=12'd350; ho_rom[742]=12'd352; ho_rom[743]=12'd354;
    ho_rom[744]=12'd356; ho_rom[745]=12'd359; ho_rom[746]=12'd361; ho_rom[747]=12'd364; ho_rom[748]=12'd366; ho_rom[749]=12'd369; ho_rom[750]=12'd372; ho_rom[751]=12'd375;
    ho_rom[752]=12'd379; ho_rom[753]=12'd382; ho_rom[754]=12'd386; ho_rom[755]=12'd390; ho_rom[756]=12'd394; ho_rom[757]=12'd399; ho_rom[758]=12'd404; ho_rom[759]=12'd410;
    ho_rom[760]=12'd416; ho_rom[761]=12'd424; ho_rom[762]=12'd432; ho_rom[763]=12'd442; ho_rom[764]=12'd454; ho_rom[765]=12'd471; ho_rom[766]=12'd496; ho_rom[767]=12'd549;
    ho_rom[768]=12'd51; ho_rom[769]=12'd62; ho_rom[770]=12'd68; ho_rom[771]=12'd73; ho_rom[772]=12'd76; ho_rom[773]=12'd80; ho_rom[774]=12'd83; ho_rom[775]=12'd85;
    ho_rom[776]=12'd88; ho_rom[777]=12'd90; ho_rom[778]=12'd92; ho_rom[779]=12'd94; ho_rom[780]=12'd96; ho_rom[781]=12'd98; ho_rom[782]=12'd100; ho_rom[783]=12'd102;
    ho_rom[784]=12'd103; ho_rom[785]=12'd105; ho_rom[786]=12'd106; ho_rom[787]=12'd108; ho_rom[788]=12'd109; ho_rom[789]=12'd111; ho_rom[790]=12'd112; ho_rom[791]=12'd114;
    ho_rom[792]=12'd115; ho_rom[793]=12'd116; ho_rom[794]=12'd118; ho_rom[795]=12'd119; ho_rom[796]=12'd120; ho_rom[797]=12'd121; ho_rom[798]=12'd123; ho_rom[799]=12'd124;
    ho_rom[800]=12'd125; ho_rom[801]=12'd126; ho_rom[802]=12'd128; ho_rom[803]=12'd129; ho_rom[804]=12'd130; ho_rom[805]=12'd131; ho_rom[806]=12'd132; ho_rom[807]=12'd133;
    ho_rom[808]=12'd134; ho_rom[809]=12'd136; ho_rom[810]=12'd137; ho_rom[811]=12'd138; ho_rom[812]=12'd139; ho_rom[813]=12'd140; ho_rom[814]=12'd141; ho_rom[815]=12'd142;
    ho_rom[816]=12'd143; ho_rom[817]=12'd144; ho_rom[818]=12'd145; ho_rom[819]=12'd146; ho_rom[820]=12'd147; ho_rom[821]=12'd148; ho_rom[822]=12'd149; ho_rom[823]=12'd150;
    ho_rom[824]=12'd151; ho_rom[825]=12'd152; ho_rom[826]=12'd153; ho_rom[827]=12'd154; ho_rom[828]=12'd155; ho_rom[829]=12'd156; ho_rom[830]=12'd157; ho_rom[831]=12'd158;
    ho_rom[832]=12'd159; ho_rom[833]=12'd160; ho_rom[834]=12'd161; ho_rom[835]=12'd162; ho_rom[836]=12'd163; ho_rom[837]=12'd164; ho_rom[838]=12'd165; ho_rom[839]=12'd166;
    ho_rom[840]=12'd167; ho_rom[841]=12'd168; ho_rom[842]=12'd169; ho_rom[843]=12'd170; ho_rom[844]=12'd171; ho_rom[845]=12'd172; ho_rom[846]=12'd173; ho_rom[847]=12'd174;
    ho_rom[848]=12'd175; ho_rom[849]=12'd176; ho_rom[850]=12'd177; ho_rom[851]=12'd178; ho_rom[852]=12'd179; ho_rom[853]=12'd180; ho_rom[854]=12'd181; ho_rom[855]=12'd182;
    ho_rom[856]=12'd183; ho_rom[857]=12'd184; ho_rom[858]=12'd185; ho_rom[859]=12'd186; ho_rom[860]=12'd187; ho_rom[861]=12'd188; ho_rom[862]=12'd189; ho_rom[863]=12'd190;
    ho_rom[864]=12'd191; ho_rom[865]=12'd192; ho_rom[866]=12'd193; ho_rom[867]=12'd194; ho_rom[868]=12'd195; ho_rom[869]=12'd196; ho_rom[870]=12'd197; ho_rom[871]=12'd198;
    ho_rom[872]=12'd199; ho_rom[873]=12'd200; ho_rom[874]=12'd201; ho_rom[875]=12'd202; ho_rom[876]=12'd203; ho_rom[877]=12'd205; ho_rom[878]=12'd206; ho_rom[879]=12'd207;
    ho_rom[880]=12'd208; ho_rom[881]=12'd209; ho_rom[882]=12'd210; ho_rom[883]=12'd211; ho_rom[884]=12'd212; ho_rom[885]=12'd213; ho_rom[886]=12'd214; ho_rom[887]=12'd215;
    ho_rom[888]=12'd216; ho_rom[889]=12'd217; ho_rom[890]=12'd218; ho_rom[891]=12'd220; ho_rom[892]=12'd221; ho_rom[893]=12'd222; ho_rom[894]=12'd223; ho_rom[895]=12'd224;
    ho_rom[896]=12'd225; ho_rom[897]=12'd226; ho_rom[898]=12'd227; ho_rom[899]=12'd229; ho_rom[900]=12'd230; ho_rom[901]=12'd231; ho_rom[902]=12'd232; ho_rom[903]=12'd233;
    ho_rom[904]=12'd234; ho_rom[905]=12'd236; ho_rom[906]=12'd237; ho_rom[907]=12'd238; ho_rom[908]=12'd239; ho_rom[909]=12'd240; ho_rom[910]=12'd242; ho_rom[911]=12'd243;
    ho_rom[912]=12'd244; ho_rom[913]=12'd245; ho_rom[914]=12'd246; ho_rom[915]=12'd248; ho_rom[916]=12'd249; ho_rom[917]=12'd250; ho_rom[918]=12'd252; ho_rom[919]=12'd253;
    ho_rom[920]=12'd254; ho_rom[921]=12'd256; ho_rom[922]=12'd257; ho_rom[923]=12'd258; ho_rom[924]=12'd260; ho_rom[925]=12'd261; ho_rom[926]=12'd262; ho_rom[927]=12'd264;
    ho_rom[928]=12'd265; ho_rom[929]=12'd266; ho_rom[930]=12'd268; ho_rom[931]=12'd269; ho_rom[932]=12'd271; ho_rom[933]=12'd272; ho_rom[934]=12'd274; ho_rom[935]=12'd275;
    ho_rom[936]=12'd277; ho_rom[937]=12'd278; ho_rom[938]=12'd280; ho_rom[939]=12'd281; ho_rom[940]=12'd283; ho_rom[941]=12'd284; ho_rom[942]=12'd286; ho_rom[943]=12'd288;
    ho_rom[944]=12'd289; ho_rom[945]=12'd291; ho_rom[946]=12'd293; ho_rom[947]=12'd294; ho_rom[948]=12'd296; ho_rom[949]=12'd298; ho_rom[950]=12'd299; ho_rom[951]=12'd301;
    ho_rom[952]=12'd303; ho_rom[953]=12'd305; ho_rom[954]=12'd307; ho_rom[955]=12'd308; ho_rom[956]=12'd310; ho_rom[957]=12'd312; ho_rom[958]=12'd314; ho_rom[959]=12'd316;
    ho_rom[960]=12'd318; ho_rom[961]=12'd320; ho_rom[962]=12'd322; ho_rom[963]=12'd324; ho_rom[964]=12'd326; ho_rom[965]=12'd329; ho_rom[966]=12'd331; ho_rom[967]=12'd333;
    ho_rom[968]=12'd335; ho_rom[969]=12'd338; ho_rom[970]=12'd340; ho_rom[971]=12'd342; ho_rom[972]=12'd345; ho_rom[973]=12'd347; ho_rom[974]=12'd350; ho_rom[975]=12'd352;
    ho_rom[976]=12'd355; ho_rom[977]=12'd358; ho_rom[978]=12'd360; ho_rom[979]=12'd363; ho_rom[980]=12'd366; ho_rom[981]=12'd369; ho_rom[982]=12'd372; ho_rom[983]=12'd375;
    ho_rom[984]=12'd378; ho_rom[985]=12'd381; ho_rom[986]=12'd385; ho_rom[987]=12'd388; ho_rom[988]=12'd392; ho_rom[989]=12'd395; ho_rom[990]=12'd399; ho_rom[991]=12'd403;
    ho_rom[992]=12'd407; ho_rom[993]=12'd411; ho_rom[994]=12'd415; ho_rom[995]=12'd419; ho_rom[996]=12'd424; ho_rom[997]=12'd428; ho_rom[998]=12'd433; ho_rom[999]=12'd438;
    ho_rom[1000]=12'd444; ho_rom[1001]=12'd449; ho_rom[1002]=12'd455; ho_rom[1003]=12'd461; ho_rom[1004]=12'd467; ho_rom[1005]=12'd474; ho_rom[1006]=12'd481; ho_rom[1007]=12'd489;
    ho_rom[1008]=12'd497; ho_rom[1009]=12'd505; ho_rom[1010]=12'd514; ho_rom[1011]=12'd524; ho_rom[1012]=12'd535; ho_rom[1013]=12'd547; ho_rom[1014]=12'd560; ho_rom[1015]=12'd575;
    ho_rom[1016]=12'd591; ho_rom[1017]=12'd611; ho_rom[1018]=12'd633; ho_rom[1019]=12'd660; ho_rom[1020]=12'd695; ho_rom[1021]=12'd742; ho_rom[1022]=12'd816; ho_rom[1023]=12'd984;
    ho_rom[1024]=12'd0; ho_rom[1025]=12'd2; ho_rom[1026]=12'd3; ho_rom[1027]=12'd4; ho_rom[1028]=12'd5; ho_rom[1029]=12'd6; ho_rom[1030]=12'd7; ho_rom[1031]=12'd8;
    ho_rom[1032]=12'd9; ho_rom[1033]=12'd10; ho_rom[1034]=12'd11; ho_rom[1035]=12'd12; ho_rom[1036]=12'd13; ho_rom[1037]=12'd14; ho_rom[1038]=12'd15; ho_rom[1039]=12'd16;
    ho_rom[1040]=12'd17; ho_rom[1041]=12'd18; ho_rom[1042]=12'd19; ho_rom[1043]=12'd20; ho_rom[1044]=12'd21; ho_rom[1045]=12'd22; ho_rom[1046]=12'd24; ho_rom[1047]=12'd25;
    ho_rom[1048]=12'd26; ho_rom[1049]=12'd27; ho_rom[1050]=12'd28; ho_rom[1051]=12'd29; ho_rom[1052]=12'd30; ho_rom[1053]=12'd31; ho_rom[1054]=12'd32; ho_rom[1055]=12'd34;
    ho_rom[1056]=12'd35; ho_rom[1057]=12'd36; ho_rom[1058]=12'd37; ho_rom[1059]=12'd38; ho_rom[1060]=12'd39; ho_rom[1061]=12'd41; ho_rom[1062]=12'd42; ho_rom[1063]=12'd43;
    ho_rom[1064]=12'd44; ho_rom[1065]=12'd45; ho_rom[1066]=12'd46; ho_rom[1067]=12'd48; ho_rom[1068]=12'd49; ho_rom[1069]=12'd50; ho_rom[1070]=12'd51; ho_rom[1071]=12'd53;
    ho_rom[1072]=12'd54; ho_rom[1073]=12'd55; ho_rom[1074]=12'd56; ho_rom[1075]=12'd57; ho_rom[1076]=12'd59; ho_rom[1077]=12'd60; ho_rom[1078]=12'd61; ho_rom[1079]=12'd63;
    ho_rom[1080]=12'd64; ho_rom[1081]=12'd65; ho_rom[1082]=12'd66; ho_rom[1083]=12'd68; ho_rom[1084]=12'd69; ho_rom[1085]=12'd70; ho_rom[1086]=12'd72; ho_rom[1087]=12'd73;
    ho_rom[1088]=12'd74; ho_rom[1089]=12'd76; ho_rom[1090]=12'd77; ho_rom[1091]=12'd78; ho_rom[1092]=12'd80; ho_rom[1093]=12'd81; ho_rom[1094]=12'd82; ho_rom[1095]=12'd84;
    ho_rom[1096]=12'd85; ho_rom[1097]=12'd87; ho_rom[1098]=12'd88; ho_rom[1099]=12'd89; ho_rom[1100]=12'd91; ho_rom[1101]=12'd92; ho_rom[1102]=12'd94; ho_rom[1103]=12'd95;
    ho_rom[1104]=12'd97; ho_rom[1105]=12'd98; ho_rom[1106]=12'd100; ho_rom[1107]=12'd101; ho_rom[1108]=12'd103; ho_rom[1109]=12'd104; ho_rom[1110]=12'd106; ho_rom[1111]=12'd107;
    ho_rom[1112]=12'd109; ho_rom[1113]=12'd110; ho_rom[1114]=12'd112; ho_rom[1115]=12'd113; ho_rom[1116]=12'd115; ho_rom[1117]=12'd116; ho_rom[1118]=12'd118; ho_rom[1119]=12'd119;
    ho_rom[1120]=12'd121; ho_rom[1121]=12'd123; ho_rom[1122]=12'd124; ho_rom[1123]=12'd126; ho_rom[1124]=12'd128; ho_rom[1125]=12'd129; ho_rom[1126]=12'd131; ho_rom[1127]=12'd133;
    ho_rom[1128]=12'd134; ho_rom[1129]=12'd136; ho_rom[1130]=12'd138; ho_rom[1131]=12'd139; ho_rom[1132]=12'd141; ho_rom[1133]=12'd143; ho_rom[1134]=12'd145; ho_rom[1135]=12'd146;
    ho_rom[1136]=12'd148; ho_rom[1137]=12'd150; ho_rom[1138]=12'd152; ho_rom[1139]=12'd154; ho_rom[1140]=12'd155; ho_rom[1141]=12'd157; ho_rom[1142]=12'd159; ho_rom[1143]=12'd161;
    ho_rom[1144]=12'd163; ho_rom[1145]=12'd165; ho_rom[1146]=12'd167; ho_rom[1147]=12'd169; ho_rom[1148]=12'd170; ho_rom[1149]=12'd172; ho_rom[1150]=12'd174; ho_rom[1151]=12'd176;
    ho_rom[1152]=12'd178; ho_rom[1153]=12'd180; ho_rom[1154]=12'd182; ho_rom[1155]=12'd185; ho_rom[1156]=12'd187; ho_rom[1157]=12'd189; ho_rom[1158]=12'd191; ho_rom[1159]=12'd193;
    ho_rom[1160]=12'd195; ho_rom[1161]=12'd197; ho_rom[1162]=12'd199; ho_rom[1163]=12'd202; ho_rom[1164]=12'd204; ho_rom[1165]=12'd206; ho_rom[1166]=12'd208; ho_rom[1167]=12'd210;
    ho_rom[1168]=12'd213; ho_rom[1169]=12'd215; ho_rom[1170]=12'd217; ho_rom[1171]=12'd220; ho_rom[1172]=12'd222; ho_rom[1173]=12'd224; ho_rom[1174]=12'd227; ho_rom[1175]=12'd229;
    ho_rom[1176]=12'd232; ho_rom[1177]=12'd234; ho_rom[1178]=12'd237; ho_rom[1179]=12'd239; ho_rom[1180]=12'd242; ho_rom[1181]=12'd244; ho_rom[1182]=12'd247; ho_rom[1183]=12'd250;
    ho_rom[1184]=12'd252; ho_rom[1185]=12'd255; ho_rom[1186]=12'd258; ho_rom[1187]=12'd261; ho_rom[1188]=12'd263; ho_rom[1189]=12'd266; ho_rom[1190]=12'd269; ho_rom[1191]=12'd272;
    ho_rom[1192]=12'd275; ho_rom[1193]=12'd278; ho_rom[1194]=12'd281; ho_rom[1195]=12'd284; ho_rom[1196]=12'd287; ho_rom[1197]=12'd290; ho_rom[1198]=12'd293; ho_rom[1199]=12'd296;
    ho_rom[1200]=12'd299; ho_rom[1201]=12'd303; ho_rom[1202]=12'd306; ho_rom[1203]=12'd309; ho_rom[1204]=12'd313; ho_rom[1205]=12'd316; ho_rom[1206]=12'd319; ho_rom[1207]=12'd323;
    ho_rom[1208]=12'd327; ho_rom[1209]=12'd330; ho_rom[1210]=12'd334; ho_rom[1211]=12'd337; ho_rom[1212]=12'd341; ho_rom[1213]=12'd345; ho_rom[1214]=12'd349; ho_rom[1215]=12'd353;
    ho_rom[1216]=12'd357; ho_rom[1217]=12'd361; ho_rom[1218]=12'd365; ho_rom[1219]=12'd369; ho_rom[1220]=12'd374; ho_rom[1221]=12'd378; ho_rom[1222]=12'd382; ho_rom[1223]=12'd387;
    ho_rom[1224]=12'd391; ho_rom[1225]=12'd396; ho_rom[1226]=12'd401; ho_rom[1227]=12'd406; ho_rom[1228]=12'd411; ho_rom[1229]=12'd416; ho_rom[1230]=12'd421; ho_rom[1231]=12'd426;
    ho_rom[1232]=12'd431; ho_rom[1233]=12'd437; ho_rom[1234]=12'd442; ho_rom[1235]=12'd448; ho_rom[1236]=12'd454; ho_rom[1237]=12'd460; ho_rom[1238]=12'd466; ho_rom[1239]=12'd472;
    ho_rom[1240]=12'd478; ho_rom[1241]=12'd485; ho_rom[1242]=12'd492; ho_rom[1243]=12'd499; ho_rom[1244]=12'd506; ho_rom[1245]=12'd513; ho_rom[1246]=12'd521; ho_rom[1247]=12'd528;
    ho_rom[1248]=12'd536; ho_rom[1249]=12'd545; ho_rom[1250]=12'd553; ho_rom[1251]=12'd562; ho_rom[1252]=12'd571; ho_rom[1253]=12'd581; ho_rom[1254]=12'd591; ho_rom[1255]=12'd601;
    ho_rom[1256]=12'd611; ho_rom[1257]=12'd623; ho_rom[1258]=12'd634; ho_rom[1259]=12'd646; ho_rom[1260]=12'd659; ho_rom[1261]=12'd673; ho_rom[1262]=12'd687; ho_rom[1263]=12'd702;
    ho_rom[1264]=12'd718; ho_rom[1265]=12'd735; ho_rom[1266]=12'd753; ho_rom[1267]=12'd773; ho_rom[1268]=12'd794; ho_rom[1269]=12'd818; ho_rom[1270]=12'd843; ho_rom[1271]=12'd872;
    ho_rom[1272]=12'd904; ho_rom[1273]=12'd941; ho_rom[1274]=12'd983; ho_rom[1275]=12'd1035; ho_rom[1276]=12'd1099; ho_rom[1277]=12'd1185; ho_rom[1278]=12'd1316; ho_rom[1279]=12'd1598;
    ho_rom[1280]=12'd0; ho_rom[1281]=12'd0; ho_rom[1282]=12'd0; ho_rom[1283]=12'd0; ho_rom[1284]=12'd0; ho_rom[1285]=12'd0; ho_rom[1286]=12'd0; ho_rom[1287]=12'd1;
    ho_rom[1288]=12'd1; ho_rom[1289]=12'd1; ho_rom[1290]=12'd1; ho_rom[1291]=12'd1; ho_rom[1292]=12'd1; ho_rom[1293]=12'd1; ho_rom[1294]=12'd2; ho_rom[1295]=12'd2;
    ho_rom[1296]=12'd2; ho_rom[1297]=12'd2; ho_rom[1298]=12'd2; ho_rom[1299]=12'd3; ho_rom[1300]=12'd3; ho_rom[1301]=12'd3; ho_rom[1302]=12'd3; ho_rom[1303]=12'd4;
    ho_rom[1304]=12'd4; ho_rom[1305]=12'd4; ho_rom[1306]=12'd5; ho_rom[1307]=12'd5; ho_rom[1308]=12'd5; ho_rom[1309]=12'd5; ho_rom[1310]=12'd6; ho_rom[1311]=12'd6;
    ho_rom[1312]=12'd6; ho_rom[1313]=12'd7; ho_rom[1314]=12'd7; ho_rom[1315]=12'd8; ho_rom[1316]=12'd8; ho_rom[1317]=12'd8; ho_rom[1318]=12'd9; ho_rom[1319]=12'd9;
    ho_rom[1320]=12'd10; ho_rom[1321]=12'd10; ho_rom[1322]=12'd10; ho_rom[1323]=12'd11; ho_rom[1324]=12'd11; ho_rom[1325]=12'd12; ho_rom[1326]=12'd12; ho_rom[1327]=12'd13;
    ho_rom[1328]=12'd13; ho_rom[1329]=12'd14; ho_rom[1330]=12'd14; ho_rom[1331]=12'd15; ho_rom[1332]=12'd15; ho_rom[1333]=12'd16; ho_rom[1334]=12'd16; ho_rom[1335]=12'd17;
    ho_rom[1336]=12'd18; ho_rom[1337]=12'd18; ho_rom[1338]=12'd19; ho_rom[1339]=12'd19; ho_rom[1340]=12'd20; ho_rom[1341]=12'd21; ho_rom[1342]=12'd21; ho_rom[1343]=12'd22;
    ho_rom[1344]=12'd23; ho_rom[1345]=12'd23; ho_rom[1346]=12'd24; ho_rom[1347]=12'd25; ho_rom[1348]=12'd25; ho_rom[1349]=12'd26; ho_rom[1350]=12'd27; ho_rom[1351]=12'd28;
    ho_rom[1352]=12'd28; ho_rom[1353]=12'd29; ho_rom[1354]=12'd30; ho_rom[1355]=12'd31; ho_rom[1356]=12'd31; ho_rom[1357]=12'd32; ho_rom[1358]=12'd33; ho_rom[1359]=12'd34;
    ho_rom[1360]=12'd35; ho_rom[1361]=12'd36; ho_rom[1362]=12'd37; ho_rom[1363]=12'd37; ho_rom[1364]=12'd38; ho_rom[1365]=12'd39; ho_rom[1366]=12'd40; ho_rom[1367]=12'd41;
    ho_rom[1368]=12'd42; ho_rom[1369]=12'd43; ho_rom[1370]=12'd44; ho_rom[1371]=12'd45; ho_rom[1372]=12'd46; ho_rom[1373]=12'd47; ho_rom[1374]=12'd48; ho_rom[1375]=12'd49;
    ho_rom[1376]=12'd50; ho_rom[1377]=12'd52; ho_rom[1378]=12'd53; ho_rom[1379]=12'd54; ho_rom[1380]=12'd55; ho_rom[1381]=12'd56; ho_rom[1382]=12'd57; ho_rom[1383]=12'd59;
    ho_rom[1384]=12'd60; ho_rom[1385]=12'd61; ho_rom[1386]=12'd62; ho_rom[1387]=12'd64; ho_rom[1388]=12'd65; ho_rom[1389]=12'd66; ho_rom[1390]=12'd67; ho_rom[1391]=12'd69;
    ho_rom[1392]=12'd70; ho_rom[1393]=12'd72; ho_rom[1394]=12'd73; ho_rom[1395]=12'd75; ho_rom[1396]=12'd76; ho_rom[1397]=12'd77; ho_rom[1398]=12'd79; ho_rom[1399]=12'd81;
    ho_rom[1400]=12'd82; ho_rom[1401]=12'd84; ho_rom[1402]=12'd85; ho_rom[1403]=12'd87; ho_rom[1404]=12'd89; ho_rom[1405]=12'd90; ho_rom[1406]=12'd92; ho_rom[1407]=12'd94;
    ho_rom[1408]=12'd95; ho_rom[1409]=12'd97; ho_rom[1410]=12'd99; ho_rom[1411]=12'd101; ho_rom[1412]=12'd103; ho_rom[1413]=12'd105; ho_rom[1414]=12'd106; ho_rom[1415]=12'd108;
    ho_rom[1416]=12'd110; ho_rom[1417]=12'd112; ho_rom[1418]=12'd114; ho_rom[1419]=12'd117; ho_rom[1420]=12'd119; ho_rom[1421]=12'd121; ho_rom[1422]=12'd123; ho_rom[1423]=12'd125;
    ho_rom[1424]=12'd127; ho_rom[1425]=12'd130; ho_rom[1426]=12'd132; ho_rom[1427]=12'd134; ho_rom[1428]=12'd137; ho_rom[1429]=12'd139; ho_rom[1430]=12'd142; ho_rom[1431]=12'd144;
    ho_rom[1432]=12'd147; ho_rom[1433]=12'd149; ho_rom[1434]=12'd152; ho_rom[1435]=12'd155; ho_rom[1436]=12'd157; ho_rom[1437]=12'd160; ho_rom[1438]=12'd163; ho_rom[1439]=12'd166;
    ho_rom[1440]=12'd169; ho_rom[1441]=12'd172; ho_rom[1442]=12'd175; ho_rom[1443]=12'd178; ho_rom[1444]=12'd181; ho_rom[1445]=12'd184; ho_rom[1446]=12'd188; ho_rom[1447]=12'd191;
    ho_rom[1448]=12'd194; ho_rom[1449]=12'd198; ho_rom[1450]=12'd201; ho_rom[1451]=12'd205; ho_rom[1452]=12'd208; ho_rom[1453]=12'd212; ho_rom[1454]=12'd216; ho_rom[1455]=12'd220;
    ho_rom[1456]=12'd224; ho_rom[1457]=12'd228; ho_rom[1458]=12'd232; ho_rom[1459]=12'd236; ho_rom[1460]=12'd240; ho_rom[1461]=12'd244; ho_rom[1462]=12'd249; ho_rom[1463]=12'd253;
    ho_rom[1464]=12'd258; ho_rom[1465]=12'd263; ho_rom[1466]=12'd267; ho_rom[1467]=12'd272; ho_rom[1468]=12'd277; ho_rom[1469]=12'd283; ho_rom[1470]=12'd288; ho_rom[1471]=12'd293;
    ho_rom[1472]=12'd299; ho_rom[1473]=12'd304; ho_rom[1474]=12'd310; ho_rom[1475]=12'd316; ho_rom[1476]=12'd322; ho_rom[1477]=12'd328; ho_rom[1478]=12'd334; ho_rom[1479]=12'd341;
    ho_rom[1480]=12'd348; ho_rom[1481]=12'd354; ho_rom[1482]=12'd361; ho_rom[1483]=12'd369; ho_rom[1484]=12'd376; ho_rom[1485]=12'd384; ho_rom[1486]=12'd392; ho_rom[1487]=12'd400;
    ho_rom[1488]=12'd408; ho_rom[1489]=12'd416; ho_rom[1490]=12'd425; ho_rom[1491]=12'd434; ho_rom[1492]=12'd443; ho_rom[1493]=12'd453; ho_rom[1494]=12'd463; ho_rom[1495]=12'd473;
    ho_rom[1496]=12'd484; ho_rom[1497]=12'd495; ho_rom[1498]=12'd506; ho_rom[1499]=12'd518; ho_rom[1500]=12'd530; ho_rom[1501]=12'd543; ho_rom[1502]=12'd556; ho_rom[1503]=12'd570;
    ho_rom[1504]=12'd584; ho_rom[1505]=12'd599; ho_rom[1506]=12'd615; ho_rom[1507]=12'd631; ho_rom[1508]=12'd648; ho_rom[1509]=12'd666; ho_rom[1510]=12'd684; ho_rom[1511]=12'd704;
    ho_rom[1512]=12'd725; ho_rom[1513]=12'd747; ho_rom[1514]=12'd770; ho_rom[1515]=12'd794; ho_rom[1516]=12'd820; ho_rom[1517]=12'd848; ho_rom[1518]=12'd878; ho_rom[1519]=12'd910;
    ho_rom[1520]=12'd944; ho_rom[1521]=12'd981; ho_rom[1522]=12'd1022; ho_rom[1523]=12'd1066; ho_rom[1524]=12'd1115; ho_rom[1525]=12'd1170; ho_rom[1526]=12'd1230; ho_rom[1527]=12'd1300;
    ho_rom[1528]=12'd1379; ho_rom[1529]=12'd1472; ho_rom[1530]=12'd1584; ho_rom[1531]=12'd1723; ho_rom[1532]=12'd1903; ho_rom[1533]=12'd2155; ho_rom[1534]=12'd2560; ho_rom[1535]=12'd3522;
end

// ---- λ-DEPENDENT tables: address = {lam_sel[1:0], water[1:0], dist[3:0]}
//      lam_sel: 0=450 1=532 1=650 nm
reg [23:0] psig_rom [0:143];
initial begin
    psig_rom[0]=24'd174111; psig_rom[1]=24'd101129; psig_rom[2]=24'd58685; psig_rom[3]=24'd34036;
    psig_rom[4]=24'd19734; psig_rom[5]=24'd10442; psig_rom[6]=24'd4447; psig_rom[7]=24'd1973;
    psig_rom[8]=24'd904; psig_rom[9]=24'd424; psig_rom[10]=24'd203; psig_rom[11]=24'd99;
    psig_rom[12]=24'd49; psig_rom[13]=24'd24; psig_rom[14]=24'd12; psig_rom[15]=24'd6;
    psig_rom[16]=24'd142859; psig_rom[17]=24'd68023; psig_rom[18]=24'd32351; psig_rom[19]=24'd15377;
    psig_rom[20]=24'd7307; psig_rom[21]=24'd2393; psig_rom[22]=24'd784; psig_rom[23]=24'd257;
    psig_rom[24]=24'd84; psig_rom[25]=24'd28; psig_rom[26]=24'd9; psig_rom[27]=24'd3;
    psig_rom[28]=24'd1; psig_rom[29]=24'd0; psig_rom[30]=24'd0; psig_rom[31]=24'd0;
    psig_rom[32]=24'd85740; psig_rom[33]=24'd24450; psig_rom[34]=24'd6963; psig_rom[35]=24'd1982;
    psig_rom[36]=24'd564; psig_rom[37]=24'd161; psig_rom[38]=24'd46; psig_rom[39]=24'd13;
    psig_rom[40]=24'd4; psig_rom[41]=24'd1; psig_rom[42]=24'd0; psig_rom[43]=24'd0;
    psig_rom[44]=24'd0; psig_rom[45]=24'd0; psig_rom[46]=24'd0; psig_rom[47]=24'd0;
    psig_rom[48]=24'd158208; psig_rom[49]=24'd83463; psig_rom[50]=24'd43984; psig_rom[51]=24'd23166;
    psig_rom[52]=24'd12198; psig_rom[53]=24'd5861; psig_rom[54]=24'd2267; psig_rom[55]=24'd914;
    psig_rom[56]=24'd380; psig_rom[57]=24'd162; psig_rom[58]=24'd70; psig_rom[59]=24'd31;
    psig_rom[60]=24'd14; psig_rom[61]=24'd6; psig_rom[62]=24'd3; psig_rom[63]=24'd1;
    psig_rom[64]=24'd152814; psig_rom[65]=24'd77857; psig_rom[66]=24'd39623; psig_rom[67]=24'd20154;
    psig_rom[68]=24'd10248; psig_rom[69]=24'd3715; psig_rom[70]=24'd1347; psig_rom[71]=24'd488;
    psig_rom[72]=24'd177; psig_rom[73]=24'd64; psig_rom[74]=24'd23; psig_rom[75]=24'd7;
    psig_rom[76]=24'd2; psig_rom[77]=24'd1; psig_rom[78]=24'd0; psig_rom[79]=24'd0;
    psig_rom[80]=24'd118640; psig_rom[81]=24'd46875; psig_rom[82]=24'd18497; psig_rom[83]=24'd7295;
    psig_rom[84]=24'd2876; psig_rom[85]=24'd1134; psig_rom[86]=24'd447; psig_rom[87]=24'd176;
    psig_rom[88]=24'd70; psig_rom[89]=24'd27; psig_rom[90]=24'd11; psig_rom[91]=24'd4;
    psig_rom[92]=24'd1; psig_rom[93]=24'd0; psig_rom[94]=24'd0; psig_rom[95]=24'd0;
    psig_rom[96]=24'd56835; psig_rom[97]=24'd10729; psig_rom[98]=24'd2023; psig_rom[99]=24'd381;
    psig_rom[100]=24'd72; psig_rom[101]=24'd12; psig_rom[102]=24'd2; psig_rom[103]=24'd0;
    psig_rom[104]=24'd0; psig_rom[105]=24'd0; psig_rom[106]=24'd0; psig_rom[107]=24'd0;
    psig_rom[108]=24'd0; psig_rom[109]=24'd0; psig_rom[110]=24'd0; psig_rom[111]=24'd0;
    psig_rom[112]=24'd112838; psig_rom[113]=24'd42393; psig_rom[114]=24'd15906; psig_rom[115]=24'd5965;
    psig_rom[116]=24'd2237; psig_rom[117]=24'd513; psig_rom[118]=24'd118; psig_rom[119]=24'd27;
    psig_rom[120]=24'd6; psig_rom[121]=24'd1; psig_rom[122]=24'd0; psig_rom[123]=24'd0;
    psig_rom[124]=24'd0; psig_rom[125]=24'd0; psig_rom[126]=24'd0; psig_rom[127]=24'd0;
    psig_rom[128]=24'd130168; psig_rom[129]=24'd56450; psig_rom[130]=24'd24450; psig_rom[131]=24'd10584;
    psig_rom[132]=24'd4581; psig_rom[133]=24'd1982; psig_rom[134]=24'd858; psig_rom[135]=24'd371;
    psig_rom[136]=24'd161; psig_rom[137]=24'd70; psig_rom[138]=24'd30; psig_rom[139]=24'd13;
    psig_rom[140]=24'd2; psig_rom[141]=24'd0; psig_rom[142]=24'd0; psig_rom[143]=24'd0;
end

reg [23:0] epol_rom [0:143];
initial begin
    epol_rom[0]=24'd265422; epol_rom[1]=24'd348863; epol_rom[2]=24'd420162; epol_rom[3]=24'd481087;
    epol_rom[4]=24'd533146; epol_rom[5]=24'd577631; epol_rom[6]=24'd615642; epol_rom[7]=24'd648123;
    epol_rom[8]=24'd675877; epol_rom[9]=24'd699593; epol_rom[10]=24'd719857; epol_rom[11]=24'd737174;
    epol_rom[12]=24'd751970; epol_rom[13]=24'd764614; epol_rom[14]=24'd775417; epol_rom[15]=24'd784649;
    epol_rom[16]=24'd424349; epol_rom[17]=24'd582829; epol_rom[18]=24'd680718; epol_rom[19]=24'd741180;
    epol_rom[20]=24'd778526; epol_rom[21]=24'd809572; epol_rom[22]=24'd824643; epol_rom[23]=24'd831959;
    epol_rom[24]=24'd835510; epol_rom[25]=24'd837234; epol_rom[26]=24'd838071; epol_rom[27]=24'd838478;
    epol_rom[28]=24'd838675; epol_rom[29]=24'd838770; epol_rom[30]=24'd838817; epol_rom[31]=24'd838840;
    epol_rom[32]=24'd642942; epol_rom[33]=24'd781664; epol_rom[34]=24'd822163; epol_rom[35]=24'd833986;
    epol_rom[36]=24'd837438; epol_rom[37]=24'd838445; epol_rom[38]=24'd838740; epol_rom[39]=24'd838825;
    epol_rom[40]=24'd838850; epol_rom[41]=24'd838858; epol_rom[42]=24'd838860; epol_rom[43]=24'd838861;
    epol_rom[44]=24'd838861; epol_rom[45]=24'd838861; epol_rom[46]=24'd838861; epol_rom[47]=24'd838861;
    epol_rom[48]=24'd281116; epol_rom[49]=24'd375317; epol_rom[50]=24'd453607; epol_rom[51]=24'd518675;
    epol_rom[52]=24'd572753; epol_rom[53]=24'd617698; epol_rom[54]=24'd655051; epol_rom[55]=24'd686096;
    epol_rom[56]=24'd711897; epol_rom[57]=24'd733341; epol_rom[58]=24'd751163; epol_rom[59]=24'd765974;
    epol_rom[60]=24'd778285; epol_rom[61]=24'd788516; epol_rom[62]=24'd797019; epol_rom[63]=24'd804086;
    epol_rom[64]=24'd405790; epol_rom[65]=24'd559389; epol_rom[66]=24'd658510; epol_rom[67]=24'd722476;
    epol_rom[68]=24'd763755; epol_rom[69]=24'd799926; epol_rom[70]=24'd818677; epol_rom[71]=24'd828397;
    epol_rom[72]=24'd833436; epol_rom[73]=24'd836049; epol_rom[74]=24'd837403; epol_rom[75]=24'd838105;
    epol_rom[76]=24'd838469; epol_rom[77]=24'd838658; epol_rom[78]=24'd838756; epol_rom[79]=24'd838806;
    epol_rom[80]=24'd569271; epol_rom[81]=24'd730561; epol_rom[82]=24'd795355; epol_rom[83]=24'd821384;
    epol_rom[84]=24'd831840; epol_rom[85]=24'd836040; epol_rom[86]=24'd837728; epol_rom[87]=24'd838406;
    epol_rom[88]=24'd838678; epol_rom[89]=24'd838787; epol_rom[90]=24'd838831; epol_rom[91]=24'd838849;
    epol_rom[92]=24'd838859; epol_rom[93]=24'd838860; epol_rom[94]=24'd838861; epol_rom[95]=24'd838861;
    epol_rom[96]=24'd424017; epol_rom[97]=24'd582419; epol_rom[98]=24'd680338; epol_rom[99]=24'd740867;
    epol_rom[100]=24'd778285; epol_rom[101]=24'd801415; epol_rom[102]=24'd815713; epol_rom[103]=24'd824552;
    epol_rom[104]=24'd830015; epol_rom[105]=24'd833393; epol_rom[106]=24'd835481; epol_rom[107]=24'd836771;
    epol_rom[108]=24'd837569; epol_rom[109]=24'd838062; epol_rom[110]=24'd838367; epol_rom[111]=24'd838556;
    epol_rom[112]=24'd483263; epol_rom[113]=24'd650436; epol_rom[114]=24'd739018; epol_rom[115]=24'd785956;
    epol_rom[116]=24'd810827; epol_rom[117]=24'd828048; epol_rom[118]=24'd834690; epol_rom[119]=24'd837252;
    epol_rom[120]=24'd838240; epol_rom[121]=24'd838621; epol_rom[122]=24'd838768; epol_rom[123]=24'd838825;
    epol_rom[124]=24'd838847; epol_rom[125]=24'd838856; epol_rom[126]=24'd838859; epol_rom[127]=24'd838860;
    epol_rom[128]=24'd543528; epol_rom[129]=24'd708891; epol_rom[130]=24'd781664; epol_rom[131]=24'd813690;
    epol_rom[132]=24'd827783; epol_rom[133]=24'd833986; epol_rom[134]=24'd836715; epol_rom[135]=24'd837917;
    epol_rom[136]=24'd838445; epol_rom[137]=24'd838678; epol_rom[138]=24'd838780; epol_rom[139]=24'd838825;
    epol_rom[140]=24'd838854; epol_rom[141]=24'd838859; epol_rom[142]=24'd838861; epol_rom[143]=24'd838861;
end

// nexp_inv_rom = round(32768 / E[clicks per 65,536-attempt window])
// → lets channel_monitor normalise SNR with NO divider.
// ⚠ These values are tied to the window size: the ATTEMPT_LOG2 parameter
//   of channel_monitor.v MUST be 16.
reg [15:0] nexp_inv_rom [0:143];
initial begin
    nexp_inv_rom[0]=16'd48; nexp_inv_rom[1]=16'd83; nexp_inv_rom[2]=16'd142; nexp_inv_rom[3]=16'd245;
    nexp_inv_rom[4]=16'd420; nexp_inv_rom[5]=16'd787; nexp_inv_rom[6]=16'd1798; nexp_inv_rom[7]=16'd3828;
    nexp_inv_rom[8]=16'd7478; nexp_inv_rom[9]=16'd13060; nexp_inv_rom[10]=16'd19911; nexp_inv_rom[11]=16'd26458;
    nexp_inv_rom[12]=16'd31421; nexp_inv_rom[13]=16'd34589; nexp_inv_rom[14]=16'd36404; nexp_inv_rom[15]=16'd37385;
    nexp_inv_rom[16]=16'd59; nexp_inv_rom[17]=16'd123; nexp_inv_rom[18]=16'd258; nexp_inv_rom[19]=16'd538;
    nexp_inv_rom[20]=16'd1115; nexp_inv_rom[21]=16'd3212; nexp_inv_rom[22]=16'd8373; nexp_inv_rom[23]=16'd17670;
    nexp_inv_rom[24]=16'd27764; nexp_inv_rom[25]=16'd34152; nexp_inv_rom[26]=16'd36935; nexp_inv_rom[27]=16'd38022;
    nexp_inv_rom[28]=16'd38341; nexp_inv_rom[29]=16'd38428; nexp_inv_rom[30]=16'd38452; nexp_inv_rom[31]=16'd38459;
    nexp_inv_rom[32]=16'd98; nexp_inv_rom[33]=16'd340; nexp_inv_rom[34]=16'd1168; nexp_inv_rom[35]=16'd3812;
    nexp_inv_rom[36]=16'd10722; nexp_inv_rom[37]=16'd22149; nexp_inv_rom[38]=16'd31796; nexp_inv_rom[39]=16'd36296;
    nexp_inv_rom[40]=16'd37819; nexp_inv_rom[41]=16'd38276; nexp_inv_rom[42]=16'd38409; nexp_inv_rom[43]=16'd38446;
    nexp_inv_rom[44]=16'd38460; nexp_inv_rom[45]=16'd38461; nexp_inv_rom[46]=16'd38462; nexp_inv_rom[47]=16'd38462;
    nexp_inv_rom[48]=16'd53; nexp_inv_rom[49]=16'd100; nexp_inv_rom[50]=16'd190; nexp_inv_rom[51]=16'd359;
    nexp_inv_rom[52]=16'd676; nexp_inv_rom[53]=16'd1380; nexp_inv_rom[54]=16'd3376; nexp_inv_rom[55]=16'd7412;
    nexp_inv_rom[56]=16'd14026; nexp_inv_rom[57]=16'd22069; nexp_inv_rom[58]=16'd29068; nexp_inv_rom[59]=16'd33652;
    nexp_inv_rom[60]=16'd36145; nexp_inv_rom[61]=16'd37374; nexp_inv_rom[62]=16'd37955; nexp_inv_rom[63]=16'd38226;
    nexp_inv_rom[64]=16'd55; nexp_inv_rom[65]=16'd107; nexp_inv_rom[66]=16'd211; nexp_inv_rom[67]=16'd412;
    nexp_inv_rom[68]=16'd801; nexp_inv_rom[69]=16'd2133; nexp_inv_rom[70]=16'd5361; nexp_inv_rom[71]=16'd11879;
    nexp_inv_rom[72]=16'd21237; nexp_inv_rom[73]=16'd29724; nexp_inv_rom[74]=16'd34758; nexp_inv_rom[75]=16'd37233;
    nexp_inv_rom[76]=16'd38083; nexp_inv_rom[77]=16'd38345; nexp_inv_rom[78]=16'd38425; nexp_inv_rom[79]=16'd38450;
    nexp_inv_rom[80]=16'd71; nexp_inv_rom[81]=16'd178; nexp_inv_rom[82]=16'd448; nexp_inv_rom[83]=16'd1117;
    nexp_inv_rom[84]=16'd2711; nexp_inv_rom[85]=16'd6204; nexp_inv_rom[86]=16'd12610; nexp_inv_rom[87]=16'd21269;
    nexp_inv_rom[88]=16'd29167; nexp_inv_rom[89]=16'd34169; nexp_inv_rom[90]=16'd36646; nexp_inv_rom[91]=16'd37725;
    nexp_inv_rom[92]=16'd38345; nexp_inv_rom[93]=16'd38443; nexp_inv_rom[94]=16'd38459; nexp_inv_rom[95]=16'd38461;
    nexp_inv_rom[96]=16'd147; nexp_inv_rom[97]=16'd766; nexp_inv_rom[98]=16'd3743; nexp_inv_rom[99]=16'd13992;
    nexp_inv_rom[100]=16'd28925; nexp_inv_rom[101]=16'd36397; nexp_inv_rom[102]=16'd38162; nexp_inv_rom[103]=16'd38418;
    nexp_inv_rom[104]=16'd38455; nexp_inv_rom[105]=16'd38461; nexp_inv_rom[106]=16'd38461; nexp_inv_rom[107]=16'd38462;
    nexp_inv_rom[108]=16'd38462; nexp_inv_rom[109]=16'd38462; nexp_inv_rom[110]=16'd38462; nexp_inv_rom[111]=16'd38462;
    nexp_inv_rom[112]=16'd74; nexp_inv_rom[113]=16'd197; nexp_inv_rom[114]=16'd520; nexp_inv_rom[115]=16'd1357;
    nexp_inv_rom[116]=16'd3417; nexp_inv_rom[117]=16'd11467; nexp_inv_rom[118]=16'd24968; nexp_inv_rom[119]=16'd34217;
    nexp_inv_rom[120]=16'd37397; nexp_inv_rom[121]=16'd38212; nexp_inv_rom[122]=16'd38404; nexp_inv_rom[123]=16'd38450;
    nexp_inv_rom[124]=16'd38459; nexp_inv_rom[125]=16'd38461; nexp_inv_rom[126]=16'd38461; nexp_inv_rom[127]=16'd38462;
    nexp_inv_rom[128]=16'd64; nexp_inv_rom[129]=16'd148; nexp_inv_rom[130]=16'd340; nexp_inv_rom[131]=16'd777;
    nexp_inv_rom[132]=16'd1748; nexp_inv_rom[133]=16'd3812; nexp_inv_rom[134]=16'd7797; nexp_inv_rom[135]=16'd14235;
    nexp_inv_rom[136]=16'd22149; nexp_inv_rom[137]=16'd29167; nexp_inv_rom[138]=16'd33801; nexp_inv_rom[139]=16'd36296;
    nexp_inv_rom[140]=16'd38037; nexp_inv_rom[141]=16'd38381; nexp_inv_rom[142]=16'd38446; nexp_inv_rom[143]=16'd38459;
end

// ---- λ-INDEPENDENT tables: address = {water[1:0], dist[3:0]} ----
reg [2:0] hscls_rom [0:47];
initial begin
    hscls_rom[0]=3'd0; hscls_rom[1]=3'd0; hscls_rom[2]=3'd0; hscls_rom[3]=3'd0; hscls_rom[4]=3'd0; hscls_rom[5]=3'd0; hscls_rom[6]=3'd1; hscls_rom[7]=3'd1;
    hscls_rom[8]=3'd1; hscls_rom[9]=3'd2; hscls_rom[10]=3'd3; hscls_rom[11]=3'd4; hscls_rom[12]=3'd6; hscls_rom[13]=3'd7; hscls_rom[14]=3'd7; hscls_rom[15]=3'd7;
    hscls_rom[16]=3'd0; hscls_rom[17]=3'd0; hscls_rom[18]=3'd0; hscls_rom[19]=3'd0; hscls_rom[20]=3'd0; hscls_rom[21]=3'd1; hscls_rom[22]=3'd1; hscls_rom[23]=3'd1;
    hscls_rom[24]=3'd1; hscls_rom[25]=3'd2; hscls_rom[26]=3'd4; hscls_rom[27]=3'd5; hscls_rom[28]=3'd6; hscls_rom[29]=3'd7; hscls_rom[30]=3'd7; hscls_rom[31]=3'd7;
    hscls_rom[32]=3'd1; hscls_rom[33]=3'd1; hscls_rom[34]=3'd1; hscls_rom[35]=3'd1; hscls_rom[36]=3'd1; hscls_rom[37]=3'd1; hscls_rom[38]=3'd1; hscls_rom[39]=3'd1;
    hscls_rom[40]=3'd1; hscls_rom[41]=3'd1; hscls_rom[42]=3'd2; hscls_rom[43]=3'd2; hscls_rom[44]=3'd3; hscls_rom[45]=3'd4; hscls_rom[46]=3'd4; hscls_rom[47]=3'd5;
end

// hooff_rom: range-based turbulence offset, 3-bit two's complement (−3..+3)
reg [2:0] hooff_rom [0:47];
initial begin
    hooff_rom[0]=3'd6; hooff_rom[1]=3'd7; hooff_rom[2]=3'd0; hooff_rom[3]=3'd0; hooff_rom[4]=3'd0; hooff_rom[5]=3'd1; hooff_rom[6]=3'd1; hooff_rom[7]=3'd1;
    hooff_rom[8]=3'd1; hooff_rom[9]=3'd1; hooff_rom[10]=3'd1; hooff_rom[11]=3'd2; hooff_rom[12]=3'd2; hooff_rom[13]=3'd2; hooff_rom[14]=3'd2; hooff_rom[15]=3'd2;
    hooff_rom[16]=3'd5; hooff_rom[17]=3'd5; hooff_rom[18]=3'd6; hooff_rom[19]=3'd7; hooff_rom[20]=3'd7; hooff_rom[21]=3'd7; hooff_rom[22]=3'd0; hooff_rom[23]=3'd0;
    hooff_rom[24]=3'd0; hooff_rom[25]=3'd0; hooff_rom[26]=3'd0; hooff_rom[27]=3'd1; hooff_rom[28]=3'd1; hooff_rom[29]=3'd1; hooff_rom[30]=3'd1; hooff_rom[31]=3'd1;
    hooff_rom[32]=3'd5; hooff_rom[33]=3'd5; hooff_rom[34]=3'd5; hooff_rom[35]=3'd5; hooff_rom[36]=3'd5; hooff_rom[37]=3'd5; hooff_rom[38]=3'd5; hooff_rom[39]=3'd5;
    hooff_rom[40]=3'd6; hooff_rom[41]=3'd6; hooff_rom[42]=3'd6; hooff_rom[43]=3'd6; hooff_rom[44]=3'd6; hooff_rom[45]=3'd7; hooff_rom[46]=3'd7; hooff_rom[47]=3'd7;
end

